[package]
name = "umber-desktop"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true

[[bin]]
name = "umber"
path = "src/main.rs"

[dependencies]
umber-app = { workspace = true }
env_logger = { workspace = true }
log = { workspace = true }
