//! The brush library: named, attributed presets, the set Umber ships with, and
//! the user's own set on disk.
//!
//! A preset is more than `{ name, brush }` because a library assembled from
//! several sources has to answer three questions the app cannot answer for
//! itself:
//!
//! - **Which brush is this?** — a stable [`BrushPreset::id`], so a saved
//!   selection survives a rename and so importing the same pack twice does not
//!   silently replace an edited copy.
//! - **Where did it come from?** — a [`Credit`], which is what makes shipping
//!   CC-BY material legal and CC0 material honest.
//! - **Where does it belong in the picker?** — a free-form
//!   [`BrushPreset::category`], because a flat list of two hundred brushes is
//!   not usable.
//!
//! Everything here is plain data: no GPU types, no file dialogs, no UI.

use std::collections::BTreeMap;
use std::fmt;
use std::fs;
use std::io;
use std::path::{Path, PathBuf};
use std::sync::{Arc, OnceLock};

use serde::{Deserialize, Serialize};

use crate::brush::Brush;
use crate::brushimport;
use crate::curve::ResponseCurve;
use crate::tip::TipMask;

/// The imported half of the shipped library, generated by
/// `cargo run -p umber-core --example build-brush-library`. Umber's own five
/// presets are in [`umber_defaults`] rather than in here, so the generator can
/// rewrite this file wholesale without a merge.
const BUILTIN_RON: &str = include_str!("../assets/builtin-brushes.ron");

/// The on-disk library format version. Bumped only when a change would make an
/// older Umber misread a newer file; additive fields do not need it, because
/// every field on [`Brush`] deserialises with a default.
const FORMAT_VERSION: u32 = 1;

/// Who made a preset and on what terms.
///
/// Present on everything Umber ships. CC0 material does not legally require it,
/// but recording it is how the licence stays checkable years later, when the
/// download script and its output have long since diverged.
#[derive(Clone, Debug, Default, PartialEq, Eq, Serialize, Deserialize)]
pub struct Credit {
    pub author: String,
    /// An SPDX identifier where one exists, e.g. `CC0-1.0`.
    pub licence: String,
    /// Where the original can be found.
    pub source: String,
}

/// A named brush the user can pick from the Brushes panel.
#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct BrushPreset {
    /// Stable and opaque. Umber's own are `umber/<slug>`, imports are
    /// `<pack>/<slug>`, and brushes the user saves are `user/<slug>`. Never
    /// derived from the current name at read time — renaming must not orphan a
    /// selection.
    pub id: String,
    pub name: String,
    /// Grouping for the picker. Free text rather than an enum: a brush pack
    /// brings its own categories, and Umber has no business enumerating them.
    #[serde(default)]
    pub category: String,
    #[serde(default)]
    pub credit: Option<Credit>,
    #[serde(default)]
    pub brush: Brush,
    /// The bitmap tip this brush stamps, named rather than carried.
    ///
    /// A [`crate::TipMask`] is a bitmap and the library is text, so the preset
    /// holds the *name* of a mask in the library's `tips/` directory and
    /// [`UserLibrary::tip`] resolves it. Naming rather than embedding is also
    /// what keeps two brushes cut from the same stamp sharing one file and one
    /// GPU upload.
    ///
    /// `None` is the procedural round dab, which is almost every brush — hence
    /// `skip_serializing_if`, so adding this field did not have to touch two
    /// hundred lines of the generated library.
    ///
    /// A name that resolves to nothing paints round. That is deliberate: a
    /// library copied to a machine without its tips should still give you the
    /// brush's size, spacing and dynamics rather than refusing to load.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub tip: Option<String>,
}

impl BrushPreset {
    /// A brush the user has just made in the brush editor and not yet saved.
    ///
    /// The id is left empty deliberately: [`UserLibrary::save`] allocates one
    /// that does not collide with anything already in the library, which it can
    /// only do once it knows which library the preset is going into.
    pub fn unsaved(name: impl Into<String>, brush: Brush) -> Self {
        Self {
            id: String::new(),
            name: name.into(),
            category: "My brushes".to_string(),
            credit: None,
            brush,
            tip: None,
        }
    }
}

/// The library that ships inside the binary: Umber's own presets first, then
/// everything converted from the vendored packs.
///
/// Parsed once and leaked into a `OnceLock`, so the picker can hold a
/// `&'static` slice and redraw without re-parsing two hundred brushes a frame.
pub fn builtin() -> &'static [BrushPreset] {
    static LIBRARY: OnceLock<Vec<BrushPreset>> = OnceLock::new();
    LIBRARY.get_or_init(|| {
        let mut presets = umber_defaults();
        // The embedded file is generated and covered by a test in this module,
        // so a parse failure here is a build-time mistake, not a runtime
        // condition the app could recover from.
        presets.extend(
            parse_library(BUILTIN_RON)
                .expect("the embedded brush library is generated and tested; regenerate it"),
        );
        presets
    })
}

/// Umber's own presets, in Rust rather than in the generated file so that
/// regenerating the imported library cannot lose them.
///
/// Chosen to span the parameter space rather than to be exhaustive — a hard
/// edge, a soft edge, a dense wash and a sparse one — so the sliders' effects
/// are visible by comparison.
fn umber_defaults() -> Vec<BrushPreset> {
    let credit = Credit {
        author: "Umber contributors".to_string(),
        licence: "CC0-1.0".to_string(),
        source: "https://github.com/Spillebulle/umber".to_string(),
    };
    // Sorted by style like everything else, rather than into a collection of
    // their own. A taxonomy with one group that means "ours" is not a taxonomy;
    // the `umber/` id prefix is what marks these as the defaults, and the
    // browser shows the credit on every row.
    let make = |id: &str, name: &str, brush: Brush| BrushPreset {
        id: format!("umber/{id}"),
        name: name.to_string(),
        category: crate::style::classify(name, &brush).to_string(),
        credit: Some(credit.clone()),
        brush,
        tip: None,
    };
    // A shipped brush that carries a bitmap tip, resolved out of
    // `crate::tip::builtin` rather than the user's library. Only one so far:
    // no third-party stamp pack has yet cleared the licence rule in
    // `docs/brush-sources.md`, so the one Umber ships is one Umber drew —
    // `examples/build-bitmaps.rs` generates it, and it is deliberately sparse,
    // because a stamp that paints the same under either coverage rule would
    // demonstrate nothing.
    let stamped = |id: &str, name: &str, tip: &str, brush: Brush| BrushPreset {
        tip: Some(tip.to_string()),
        ..make(id, name, brush)
    };
    vec![
        make(
            "soft-round",
            "Soft round",
            Brush {
                size: 40.0,
                hardness: 0.0,
                opacity: 0.85,
                spacing: 0.06,
                ..Brush::default()
            },
        ),
        make(
            "hard-round",
            "Hard round",
            Brush {
                size: 18.0,
                hardness: 1.0,
                opacity: 1.0,
                spacing: 0.08,
                ..Brush::default()
            },
        ),
        make(
            "ink",
            "Ink",
            Brush {
                size: 8.0,
                hardness: 0.9,
                opacity: 1.0,
                spacing: 0.04,
                stabilization: 0.6,
                min_size_ratio: 0.15,
                size_curve: ResponseCurve::EASE_IN,
                ..Brush::default()
            },
        ),
        make(
            "airbrush",
            "Airbrush",
            Brush {
                size: 90.0,
                hardness: 0.0,
                opacity: 0.18,
                spacing: 0.03,
                pressure_opacity: true,
                opacity_curve: ResponseCurve::EASE_IN,
                ..Brush::default()
            },
        ),
        make(
            "marker",
            "Marker",
            Brush {
                size: 28.0,
                hardness: 0.75,
                opacity: 0.6,
                spacing: 0.05,
                pressure_size: false,
                ..Brush::default()
            },
        ),
        stamped(
            "stipple-chalk",
            "Stipple chalk",
            "umber-stipple",
            Brush {
                size: 48.0,
                opacity: 0.9,
                // Close spacing: the stamp is a speckle, and it is the overlap
                // of many of them that makes a stroke rather than a row of
                // blobs.
                spacing: 0.06,
                pressure_size: false,
                pressure_opacity: true,
                // The stamp's brightest texel is around a half, so under a
                // `max` this brush would paint at half strength however hard it
                // was pressed. Measured, not assumed —
                // `a_shipped_stamp_paints_at_the_strength_it_was_drawn_at`.
                build_up: true,
                // Every stamp lands the same way up unless it is told not to,
                // and a repeated speckle that does is a texture with a grid in
                // it.
                dab_angle_jitter: 360.0,
                dab_ratio: 1.0,
                grain: 0.35,
                grain_scale: 180.0,
                grain_pattern: crate::brush::GrainPattern::Grit,
                ..Brush::default()
            },
        ),
    ]
}

/// The envelope the library is stored in. Private: the version is an
/// implementation detail of the file, not something a caller should hold.
#[derive(Serialize, Deserialize)]
struct LibraryFile {
    version: u32,
    presets: Vec<BrushPreset>,
}

/// Read a RON brush library.
pub fn parse_library(text: &str) -> Result<Vec<BrushPreset>, PresetError> {
    let file: LibraryFile =
        ron::from_str(text).map_err(|e| PresetError::Malformed(None, e.to_string()))?;
    if file.version > FORMAT_VERSION {
        return Err(PresetError::UnsupportedVersion(None, file.version));
    }
    Ok(file.presets)
}

/// Serialise a brush library to RON, pretty-printed so that a generated library
/// gives a readable diff when it is regenerated.
pub fn to_ron(presets: &[BrushPreset]) -> Result<String, PresetError> {
    let file = LibraryFile {
        version: FORMAT_VERSION,
        presets: presets.to_vec(),
    };
    let config = ron::ser::PrettyConfig::new().struct_names(false);
    ron::ser::to_string_pretty(&file, config)
        .map_err(|e| PresetError::Malformed(None, e.to_string()))
}

/// The user's own brushes: everything saved out of the brush editor, plus
/// anything imported from a file.
///
/// Kept entirely separate from [`builtin`]: the shipped library is read-only and
/// is replaced wholesale by an update, so writing user brushes into it would
/// lose them.
///
/// # Why a directory
///
/// This used to be a single `brushes.ron`. A bitmap tip does not go in a text
/// file, so the library is now a directory:
///
/// ```text
/// brushes/
///     brushes.ron     the presets, exactly the format it always was
///     tips/
///         <name>.png  one 8-bit greyscale coverage mask per tip
/// ```
///
/// A directory rather than a zip, which was the obvious alternative. Three
/// reasons, in order of weight:
///
/// - **A write touches only what changed.** Renaming a brush rewrites a few
///   kilobytes of RON; in a zip it rewrites the archive, tips and all. The
///   library is written on *every* edit, so that is the common case, not the
///   rare one.
/// - **The atomic-rename trick keeps working.** `write` puts
///   the RON beside itself and renames over the old one, so an interrupted
///   write cannot leave a truncated collection. Doing that for a whole zip
///   would mean rewriting and re-fsyncing every mask to change a name, and an
///   interrupted write would then be risking the tips as well.
/// - **The tips are ordinary files.** A stamp brush's content is a picture;
///   being able to open, replace or copy one with anything that opens a picture
///   is worth more than tidiness.
///
/// The old flat `brushes.ron` is migrated rather than ignored — see
/// [`UserLibrary::load_from`].
#[derive(Clone, Debug)]
pub struct UserLibrary {
    dir: PathBuf,
    presets: Vec<BrushPreset>,
    /// Every mask in `tips/`, by name.
    ///
    /// `Arc` because the same mask is handed to the editor, then to the GPU,
    /// and identity is what lets the renderer skip re-uploading it at the start
    /// of every stroke.
    tips: BTreeMap<String, Arc<TipMask>>,
    migrated: bool,
    warnings: Vec<String>,
}

impl UserLibrary {
    /// Directory name under the platform's user-data directory, and the name of
    /// the presets file inside it. They match on purpose: the directory
    /// replaced a file of that name, so finding the old one is
    /// `dir.with_extension("ron")` and nothing more.
    pub const DIR_NAME: &'static str = "brushes";
    pub const FILE_NAME: &'static str = "brushes.ron";
    const TIPS_DIR: &'static str = "tips";

    /// Where [`UserLibrary::load`] reads from: `%APPDATA%\Umber\data\brushes`
    /// on Windows, `~/.local/share/umber/brushes` on Linux,
    /// `~/Library/Application Support/Umber/brushes` on macOS. `None` on a
    /// system with no home directory.
    pub fn default_dir() -> Option<PathBuf> {
        directories::ProjectDirs::from("", "", "Umber")
            .map(|dirs| dirs.data_dir().join(Self::DIR_NAME))
    }

    /// Load the user's library from the default location.
    ///
    /// A missing directory is an empty library, not an error — that is the
    /// state every user starts in.
    pub fn load() -> Result<Self, PresetError> {
        let dir = Self::default_dir().ok_or(PresetError::NoDataDirectory)?;
        Self::load_from(dir)
    }

    /// Load from an explicit directory. Used by the tests, and by anyone who
    /// wants a second library (a project-local brush set, say).
    ///
    /// If the directory holds no `brushes.ron` but a flat one sits beside it —
    /// `…/data/brushes.ron`, where every library written before tips existed
    /// lives — that file is read and written into the new layout. The original
    /// is **left where it is**: a migration that deletes the only copy of the
    /// user's collection has to be right first time, and this one does not have
    /// to be. An older Umber on the same machine also keeps working, at the
    /// price of the two diverging, which is the better half of that trade.
    pub fn load_from(dir: impl Into<PathBuf>) -> Result<Self, PresetError> {
        let dir = dir.into();
        let file = dir.join(Self::FILE_NAME);
        let mut migrated = false;

        let text = match read_if_present(&file)? {
            Some(text) => Some(text),
            None => match read_if_present(&Self::legacy_file(&dir))? {
                Some(text) => {
                    migrated = true;
                    Some(text)
                }
                None => None,
            },
        };
        let presets = match &text {
            Some(text) => parse_library(text).map_err(|e| e.at(&file))?,
            None => Vec::new(),
        };

        let mut library = Self {
            dir,
            presets,
            tips: BTreeMap::new(),
            migrated,
            warnings: Vec::new(),
        };
        library.load_tips();
        // Only after the tips are in hand: the migrated file may name tips that
        // were never there, and `write` is what drops those references.
        //
        // A migration that cannot be written is a warning rather than a failed
        // load. The presets are already in memory and the original file has not
        // been touched, so carrying on costs nothing and refusing would put the
        // user's whole collection out of reach over a directory that could not
        // be created. `migrated` stays true, so the next run tries again.
        if migrated && let Err(e) = library.write() {
            library.warnings.push(e.to_string());
        }
        Ok(library)
    }

    /// The flat `brushes.ron` this directory replaced.
    fn legacy_file(dir: &Path) -> PathBuf {
        dir.with_extension("ron")
    }

    fn tips_dir(&self) -> PathBuf {
        self.dir.join(Self::TIPS_DIR)
    }

    /// Read every mask in `tips/`.
    ///
    /// A mask that will not decode is skipped with a warning rather than
    /// failing the load: one unreadable picture must not put the whole
    /// collection out of reach, and the brush that named it still paints — as a
    /// round one. The warning is what stops that being silent.
    fn load_tips(&mut self) {
        let Ok(entries) = fs::read_dir(self.tips_dir()) else {
            return;
        };
        for entry in entries.flatten() {
            let path = entry.path();
            if !path
                .extension()
                .is_some_and(|e| e.eq_ignore_ascii_case("png"))
            {
                continue;
            }
            let Some(name) = path.file_stem().map(|s| s.to_string_lossy().into_owned()) else {
                continue;
            };
            match fs::read(&path).map_err(|source| PresetError::Io {
                path: path.clone(),
                source,
            }) {
                Ok(bytes) => match TipMask::from_png(&bytes) {
                    Ok(mask) => {
                        self.tips.insert(name, Arc::new(mask));
                    }
                    Err(e) => self.warnings.push(format!("{}: {e}", path.display())),
                },
                Err(e) => self.warnings.push(e.to_string()),
            }
        }
    }

    /// The library's directory. Shown to the user, so it names the folder they
    /// would open rather than the RON inside it.
    pub fn dir(&self) -> &Path {
        &self.dir
    }

    /// True when this load moved a pre-tips `brushes.ron` into the directory.
    /// Worth telling the user once: their brushes are somewhere else now.
    pub fn migrated(&self) -> bool {
        self.migrated
    }

    /// Anything that could not be read but did not stop the library loading.
    pub fn warnings(&self) -> &[String] {
        &self.warnings
    }

    /// Everything saved, in the order it was added.
    pub fn presets(&self) -> &[BrushPreset] {
        &self.presets
    }

    pub fn get(&self, id: &str) -> Option<&BrushPreset> {
        self.presets.iter().find(|p| p.id == id)
    }

    /// The mask a [`BrushPreset::tip`] names, if it is here.
    pub fn tip(&self, name: &str) -> Option<&Arc<TipMask>> {
        self.tips.get(name)
    }

    /// Every mask, by name. The editor keeps its own map of these so that
    /// selecting a brush does not have to reach for the library.
    pub fn tips(&self) -> &BTreeMap<String, Arc<TipMask>> {
        &self.tips
    }

    /// Add `preset`, or replace the one that already has its id, then write the
    /// library out. Returns the id, which the caller needs when the preset
    /// arrived from [`BrushPreset::unsaved`] and had none.
    ///
    /// `tip` **replaces** the preset's bitmap tip. `None` leaves
    /// [`BrushPreset::tip`] naming whatever it already named — which is what
    /// makes "Update" on a stamp brush keep its stamp — so taking a tip off is
    /// clearing that field, not passing `None` here.
    pub fn save(
        &mut self,
        mut preset: BrushPreset,
        tip: Option<TipMask>,
    ) -> Result<String, PresetError> {
        if preset.id.is_empty() {
            preset.id = self.allocate_id(&preset.name);
        }
        if let Some(mask) = tip {
            preset.tip = Some(self.store_tip(&preset.id, mask)?);
        }
        let id = preset.id.clone();
        match self.presets.iter_mut().find(|p| p.id == id) {
            Some(existing) => *existing = preset,
            None => self.presets.push(preset),
        }
        self.write()?;
        Ok(id)
    }

    /// Remove a brush. `false` means there was nothing with that id, which is
    /// not an error — a double-click on Delete should not raise a dialog.
    pub fn delete(&mut self, id: &str) -> Result<bool, PresetError> {
        let before = self.presets.len();
        self.presets.retain(|p| p.id != id);
        if self.presets.len() == before {
            return Ok(false);
        }
        self.write()?;
        Ok(true)
    }

    /// Change a brush's display name. The id deliberately does not follow, so
    /// anything holding a selection keeps it.
    pub fn rename(&mut self, id: &str, name: impl Into<String>) -> Result<bool, PresetError> {
        let Some(preset) = self.presets.iter_mut().find(|p| p.id == id) else {
            return Ok(false);
        };
        preset.name = name.into();
        self.write()?;
        Ok(true)
    }

    /// Read a brush file from anywhere on disk, add everything in it to the
    /// library, and return what was added.
    ///
    /// One file can hold many brushes (an Umber `.ron` library), so this returns
    /// a `Vec` rather than a single preset.
    pub fn import_file(&mut self, path: &Path) -> Result<Vec<BrushPreset>, PresetError> {
        let found = brushimport::read_file(path)?;
        let mut added = Vec::with_capacity(found.len());
        for brushimport::Imported { mut preset, tip } in found {
            // Importing the same pack twice must not overwrite a copy the user
            // has since edited, so a colliding id is reallocated rather than
            // replaced. This is the one place ids are not stable across a
            // round trip, and it is the safe direction to be unstable in.
            if preset.id.is_empty() || self.presets.iter().any(|p| p.id == preset.id) {
                preset.id = self.allocate_id(&preset.name);
            }
            match tip {
                Some(mask) => preset.tip = Some(self.store_tip(&preset.id, mask)?),
                // An Umber `.ron` names its tips, and the files are not in it —
                // the exported library is text. Rather than leave a reference
                // pointing at nothing, drop it unless this library happens to
                // hold a mask by that name already, which is the case where the
                // user is re-importing their own export.
                None => {
                    if preset
                        .tip
                        .as_deref()
                        .is_some_and(|n| !self.tips.contains_key(n))
                    {
                        preset.tip = None;
                    }
                }
            }
            self.presets.push(preset.clone());
            added.push(preset);
        }
        self.write()?;
        Ok(added)
    }

    /// Write a mask into `tips/` and return the name to record on the preset.
    ///
    /// Named after the preset that first used it rather than after its contents:
    /// a hash would deduplicate identical masks, but it would also make the
    /// directory unreadable, and a stamp library is something people go and look
    /// at.
    fn store_tip(&mut self, preset_id: &str, mask: TipMask) -> Result<String, PresetError> {
        let name = self.allocate_tip_name(preset_id);
        create_dir(&self.tips_dir())?;
        let path = self.tips_dir().join(format!("{name}.png"));
        fs::write(&path, mask.to_png()?).map_err(|source| PresetError::Io {
            path: path.clone(),
            source,
        })?;
        self.tips.insert(name.clone(), Arc::new(mask));
        Ok(name)
    }

    fn allocate_id(&self, name: &str) -> String {
        let stem = slug(name);
        let stem = if stem.is_empty() { "brush" } else { &stem };
        let mut candidate = format!("user/{stem}");
        let mut n = 2;
        while self.presets.iter().any(|p| p.id == candidate) {
            candidate = format!("user/{stem}-{n}");
            n += 1;
        }
        candidate
    }

    /// A file name for a tip. Ids carry a `/`, which a file name cannot, so
    /// they go through [`slug`] — and two ids can slug to the same thing, so
    /// the result still has to be made unique.
    fn allocate_tip_name(&self, preset_id: &str) -> String {
        let stem = slug(preset_id);
        let stem = if stem.is_empty() { "tip" } else { &stem };
        let mut candidate = stem.to_string();
        let mut n = 2;
        while self.tips.contains_key(&candidate) {
            candidate = format!("{stem}-{n}");
            n += 1;
        }
        candidate
    }

    fn write(&mut self) -> Result<(), PresetError> {
        create_dir(&self.dir)?;
        let text = to_ron(&self.presets)?;
        let file = self.dir.join(Self::FILE_NAME);

        // Write beside the library and rename over it. A direct write that is
        // interrupted — a full disk, a crash, a laptop lid — leaves a truncated
        // file, and the user's whole brush collection with it; a rename is
        // atomic enough on every platform Umber runs on that the old file
        // survives instead.
        let tmp = file.with_extension("ron.tmp");
        fs::write(&tmp, text).map_err(|source| PresetError::Io {
            path: tmp.clone(),
            source,
        })?;
        fs::rename(&tmp, &file).map_err(|source| PresetError::Io {
            path: file.clone(),
            source,
        })?;

        self.prune_tips();
        Ok(())
    }

    /// Delete the masks no preset names any more.
    ///
    /// Deleting a stamp brush has to take its picture with it, or the directory
    /// grows a megabyte per discarded experiment and never gives it back. Run
    /// *after* the RON is safely written, so a failure here leaves orphaned
    /// files rather than a preset pointing at a file that has gone.
    fn prune_tips(&mut self) {
        let referenced: Vec<&str> = self
            .presets
            .iter()
            .filter_map(|preset| preset.tip.as_deref())
            .collect();
        let orphans: Vec<String> = self
            .tips
            .keys()
            .filter(|name| !referenced.contains(&name.as_str()))
            .cloned()
            .collect();
        for name in orphans {
            // Best effort: a mask that will not delete is a file left behind,
            // which is untidy, and nothing worse.
            let _ = fs::remove_file(self.tips_dir().join(format!("{name}.png")));
            self.tips.remove(&name);
        }
    }
}

fn create_dir(dir: &PathBuf) -> Result<(), PresetError> {
    if dir.as_os_str().is_empty() {
        return Ok(());
    }
    fs::create_dir_all(dir).map_err(|source| PresetError::Io {
        path: dir.clone(),
        source,
    })
}

/// Read a file, treating "not there" as `None` rather than as a failure.
fn read_if_present(path: &Path) -> Result<Option<String>, PresetError> {
    match fs::read_to_string(path) {
        Ok(text) => Ok(Some(text)),
        Err(e) if e.kind() == io::ErrorKind::NotFound => Ok(None),
        Err(source) => Err(PresetError::Io {
            path: path.to_path_buf(),
            source,
        }),
    }
}

/// Lowercase, hyphen-separated, ASCII-only. Ids end up in file paths and RON
/// strings, so anything exotic is flattened rather than escaped.
///
/// Public because the importers and the library generator all have to produce
/// ids the same way; two slug functions that disagree would be two id schemes.
pub fn slug(name: &str) -> String {
    let mut out = String::with_capacity(name.len());
    for c in name.chars() {
        if c.is_ascii_alphanumeric() {
            out.push(c.to_ascii_lowercase());
        } else if !out.ends_with('-') {
            out.push('-');
        }
    }
    out.trim_matches('-').to_string()
}

/// Anything that can go wrong reading or writing brushes.
#[derive(Debug)]
pub enum PresetError {
    /// The platform reported no user-data directory. Rare, and not something
    /// the app can fix — but it must not be a panic either.
    NoDataDirectory,
    Io {
        path: PathBuf,
        source: io::Error,
    },
    /// The file is the right kind but does not parse.
    Malformed(Option<PathBuf>, String),
    /// A library written by a newer Umber.
    UnsupportedVersion(Option<PathBuf>, u32),
    /// An extension no importer claims.
    UnknownFormat(PathBuf),
}

impl PresetError {
    /// Attach the file an error came from. Parsers work on text and cannot know
    /// the path; the code that opened the file fills it in on the way out.
    pub(crate) fn at(self, path: &Path) -> Self {
        match self {
            Self::Malformed(None, message) => Self::Malformed(Some(path.to_path_buf()), message),
            Self::UnsupportedVersion(None, v) => {
                Self::UnsupportedVersion(Some(path.to_path_buf()), v)
            }
            other => other,
        }
    }
}

impl fmt::Display for PresetError {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        fn where_(path: &Option<PathBuf>) -> String {
            match path {
                Some(p) => format!(" in {}", p.display()),
                None => String::new(),
            }
        }
        match self {
            Self::NoDataDirectory => f.write_str("this system has no user data directory"),
            Self::Io { path, source } => write!(f, "{}: {source}", path.display()),
            Self::Malformed(path, message) => {
                write!(f, "could not read the brushes{}: {message}", where_(path))
            }
            Self::UnsupportedVersion(path, v) => write!(
                f,
                "brush library version {v}{} is newer than this build of Umber understands",
                where_(path)
            ),
            Self::UnknownFormat(path) => write!(
                f,
                "{} is not a brush file Umber can read",
                path.file_name()
                    .unwrap_or(path.as_os_str())
                    .to_string_lossy()
            ),
        }
    }
}

impl std::error::Error for PresetError {
    fn source(&self) -> Option<&(dyn std::error::Error + 'static)> {
        match self {
            Self::Io { source, .. } => Some(source),
            _ => None,
        }
    }
}

/// Used by [`UserLibrary::load_from`] and by the importers, both of which get a
/// path from the caller.
pub(crate) fn read_to_string(path: &Path) -> Result<String, PresetError> {
    fs::read_to_string(path).map_err(|source| PresetError::Io {
        path: path.to_path_buf(),
        source,
    })
}

/// The same, for the formats that are not text — `.gbr` is a header and a
/// bitmap.
pub(crate) fn read_bytes(path: &Path) -> Result<Vec<u8>, PresetError> {
    fs::read(path).map_err(|source| PresetError::Io {
        path: path.to_path_buf(),
        source,
    })
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::brush::BrushMode;

    /// A scratch data directory in the OS temp directory, removed on drop, so
    /// the tests never touch the developer's real brush collection.
    ///
    /// [`Scratch::path`] is the *library directory* inside it, leaving room
    /// beside it for the flat `brushes.ron` the migration reads.
    struct Scratch(PathBuf);

    impl Scratch {
        fn new(tag: &str) -> Self {
            let dir = std::env::temp_dir()
                .join(format!("umber-preset-test-{tag}-{}", std::process::id()));
            let _ = fs::remove_dir_all(&dir);
            Self(dir)
        }

        fn path(&self) -> PathBuf {
            self.0.join(UserLibrary::DIR_NAME)
        }

        /// Where a library written before tips existed sits.
        fn legacy(&self) -> PathBuf {
            self.0.join(UserLibrary::FILE_NAME)
        }

        fn tip_file(&self, name: &str) -> PathBuf {
            self.path().join("tips").join(format!("{name}.png"))
        }
    }

    impl Drop for Scratch {
        fn drop(&mut self) {
            let _ = fs::remove_dir_all(&self.0);
        }
    }

    #[test]
    fn the_embedded_library_parses_and_is_not_empty() {
        let library = builtin();
        assert!(
            library.len() > umber_defaults().len(),
            "the generated library added nothing; regenerate it"
        );
    }

    #[test]
    fn every_shipped_preset_is_usable_and_attributed() {
        for preset in builtin() {
            let b = &preset.brush;
            assert!(
                (Brush::MIN_SIZE..=Brush::MAX_SIZE).contains(&b.size),
                "{} has an out-of-range size: {}",
                preset.name,
                b.size
            );
            assert!(
                b.step_at(0.0) > 0.0,
                "{} would spin the dab loop",
                preset.name
            );
            assert!((0.0..=1.0).contains(&b.opacity), "{} opacity", preset.name);
            assert!(
                (0.0..=1.0).contains(&b.hardness),
                "{} hardness",
                preset.name
            );
            assert!(
                b.stabilization < 1.0,
                "{} would never reach the pointer",
                preset.name
            );
            // Shipping something whose licence we cannot name is exactly the
            // mistake this field exists to prevent.
            let credit = preset
                .credit
                .as_ref()
                .unwrap_or_else(|| panic!("{} ships with no credit", preset.name));
            assert!(!credit.licence.is_empty(), "{} has no licence", preset.name);
        }
    }

    #[test]
    fn shipped_ids_are_unique() {
        // Two presets sharing an id would make a saved selection ambiguous.
        let mut ids: Vec<&str> = builtin().iter().map(|p| p.id.as_str()).collect();
        ids.sort_unstable();
        let before = ids.len();
        ids.dedup();
        assert_eq!(before, ids.len(), "duplicate preset ids in the library");
    }

    #[test]
    fn a_library_survives_a_round_trip() {
        let text = to_ron(builtin()).expect("serialise");
        let back = parse_library(&text).expect("parse");
        assert_eq!(back, builtin());
    }

    #[test]
    fn a_partial_preset_fills_in_brush_defaults() {
        // The point of `#[serde(default)]` on `Brush`: a hand-written library
        // should not have to name eleven parameters to change one.
        let text = r#"(version: 1, presets: [(id: "t/x", name: "X", brush: (size: 12.0))])"#;
        let presets = parse_library(text).expect("parse");
        assert_eq!(presets[0].brush.size, 12.0);
        assert_eq!(presets[0].brush.spacing, Brush::default().spacing);
    }

    #[test]
    fn a_newer_library_is_refused_rather_than_misread() {
        let text = r#"(version: 99, presets: [])"#;
        assert!(matches!(
            parse_library(text),
            Err(PresetError::UnsupportedVersion(_, 99))
        ));
    }

    #[test]
    fn a_missing_user_library_loads_as_empty() {
        let scratch = Scratch::new("missing");
        let library = UserLibrary::load_from(scratch.path()).expect("load");
        assert!(library.presets().is_empty());
    }

    #[test]
    fn saving_then_reloading_keeps_the_brush() {
        let scratch = Scratch::new("save");
        let mut library = UserLibrary::load_from(scratch.path()).expect("load");
        let id = library
            .save(
                BrushPreset::unsaved(
                    "My liner",
                    Brush {
                        size: 7.0,
                        mode: BrushMode::Erase,
                        ..Brush::default()
                    },
                ),
                None,
            )
            .expect("save");
        assert_eq!(id, "user/my-liner");

        let reloaded = UserLibrary::load_from(scratch.path()).expect("reload");
        let preset = reloaded.get(&id).expect("saved brush is there");
        assert_eq!(preset.name, "My liner");
        assert_eq!(preset.brush.size, 7.0);
        assert_eq!(preset.brush.mode, BrushMode::Erase);
    }

    #[test]
    fn saving_over_an_id_replaces_rather_than_duplicates() {
        let scratch = Scratch::new("replace");
        let mut library = UserLibrary::load_from(scratch.path()).expect("load");
        let id = library
            .save(BrushPreset::unsaved("Liner", Brush::default()), None)
            .expect("save");

        let mut edited = library.get(&id).expect("saved").clone();
        edited.brush.size = 99.0;
        library.save(edited, None).expect("save again");

        assert_eq!(library.presets().len(), 1);
        assert_eq!(library.get(&id).unwrap().brush.size, 99.0);
    }

    #[test]
    fn two_brushes_with_one_name_get_different_ids() {
        let scratch = Scratch::new("collide");
        let mut library = UserLibrary::load_from(scratch.path()).expect("load");
        let first = library
            .save(BrushPreset::unsaved("Liner", Brush::default()), None)
            .expect("first");
        let second = library
            .save(BrushPreset::unsaved("Liner", Brush::default()), None)
            .expect("second");
        assert_ne!(first, second);
        assert_eq!(library.presets().len(), 2);
    }

    #[test]
    fn renaming_keeps_the_id_and_deleting_reports_whether_it_hit() {
        let scratch = Scratch::new("rename");
        let mut library = UserLibrary::load_from(scratch.path()).expect("load");
        let id = library
            .save(BrushPreset::unsaved("Old", Brush::default()), None)
            .expect("save");

        assert!(library.rename(&id, "New").expect("rename"));
        assert_eq!(library.get(&id).unwrap().name, "New");
        assert!(!library.rename("user/nope", "New").expect("miss"));

        assert!(library.delete(&id).expect("delete"));
        assert!(!library.delete(&id).expect("delete again"));
        assert!(library.presets().is_empty());
    }

    /// A tip is a bitmap and the library is text; this is the whole reason the
    /// library became a directory. The mask has to come back exactly, or every
    /// stamp brush changes shape each time Umber is restarted.
    #[test]
    fn a_tipped_brush_survives_a_reload_byte_for_byte() {
        let scratch = Scratch::new("tip");
        let mut library = UserLibrary::load_from(scratch.path()).expect("load");

        let coverage: Vec<u8> = (0..(9 * 4)).map(|i| (i * 11 % 256) as u8).collect();
        let mask = TipMask::new(9, 4, coverage.clone()).expect("mask");
        let id = library
            .save(BrushPreset::unsaved("Stamp", Brush::default()), Some(mask))
            .expect("save");

        let name = library
            .get(&id)
            .and_then(|preset| preset.tip.clone())
            .expect("the saved preset names its tip");
        assert!(scratch.tip_file(&name).exists(), "no PNG was written");

        let reloaded = UserLibrary::load_from(scratch.path()).expect("reload");
        let preset = reloaded.get(&id).expect("saved brush is there");
        assert_eq!(preset.tip.as_deref(), Some(name.as_str()));
        let back = reloaded.tip(&name).expect("the mask came back");
        assert_eq!(back.width(), 9);
        assert_eq!(back.height(), 4);
        assert_eq!(back.coverage(), coverage);
    }

    #[test]
    fn updating_a_stamp_brush_keeps_its_stamp() {
        // `None` means "leave the tip alone", which is what the editor's Update
        // passes. Reading it as "no tip" would silently turn every saved stamp
        // brush round the first time its size was changed.
        let scratch = Scratch::new("keep-tip");
        let mut library = UserLibrary::load_from(scratch.path()).expect("load");
        let mask = TipMask::new(2, 2, vec![1, 2, 3, 4]).expect("mask");
        let id = library
            .save(BrushPreset::unsaved("Stamp", Brush::default()), Some(mask))
            .expect("save");

        let mut edited = library.get(&id).expect("saved").clone();
        edited.brush.size = 64.0;
        library.save(edited, None).expect("update");

        let preset = library.get(&id).expect("still there");
        assert_eq!(preset.brush.size, 64.0);
        let name = preset.tip.clone().expect("the tip is still named");
        assert_eq!(library.tip(&name).expect("mask").coverage(), [1, 2, 3, 4]);
    }

    #[test]
    fn a_tip_nobody_names_any_more_is_deleted_with_its_brush() {
        // Otherwise the directory grows a picture per discarded experiment and
        // never gives one back.
        let scratch = Scratch::new("prune");
        let mut library = UserLibrary::load_from(scratch.path()).expect("load");
        let mask = TipMask::new(2, 2, vec![255; 4]).expect("mask");
        let id = library
            .save(BrushPreset::unsaved("Stamp", Brush::default()), Some(mask))
            .expect("save");
        let name = library.get(&id).unwrap().tip.clone().expect("named");
        assert!(scratch.tip_file(&name).exists());

        library.delete(&id).expect("delete");
        assert!(
            !scratch.tip_file(&name).exists(),
            "the mask was left behind"
        );
        assert!(library.tip(&name).is_none());
    }

    #[test]
    fn clearing_the_tip_field_takes_the_tip_off() {
        let scratch = Scratch::new("untip");
        let mut library = UserLibrary::load_from(scratch.path()).expect("load");
        let mask = TipMask::new(2, 2, vec![255; 4]).expect("mask");
        let id = library
            .save(BrushPreset::unsaved("Stamp", Brush::default()), Some(mask))
            .expect("save");

        let mut round = library.get(&id).expect("saved").clone();
        round.tip = None;
        library.save(round, None).expect("save round");

        assert!(library.get(&id).unwrap().tip.is_none());
        assert!(library.tips().is_empty(), "the orphan should have gone");
    }

    #[test]
    fn importing_a_ron_drops_a_tip_reference_it_cannot_resolve() {
        // An Umber library is text, so a tip it names is not in the file. A
        // reference left pointing at nothing would be a brush that silently
        // paints round on one machine and square on another; dropping it means
        // the brush arrives round on both, which is at least honest.
        let scratch = Scratch::new("dangling");
        fs::create_dir_all(&scratch.0).expect("scratch");
        let file = scratch.0.join("exported.ron");
        fs::write(
            &file,
            r#"(version: 1, presets: [(id: "user/s", name: "S", brush: (), tip: Some("gone"))])"#,
        )
        .expect("write");

        let mut library = UserLibrary::load_from(scratch.path()).expect("load");
        let added = library.import_file(&file).expect("import");
        assert_eq!(added.len(), 1);
        assert!(added[0].tip.is_none());
    }

    /// Somebody has a `brushes.ron` from before tips existed. Losing it — or
    /// quietly leaving it behind and starting again over the top — is the
    /// failure this guards.
    #[test]
    fn a_flat_library_is_migrated_into_the_directory() {
        let scratch = Scratch::new("migrate");
        fs::create_dir_all(&scratch.0).expect("scratch");
        fs::write(
            scratch.legacy(),
            r#"(version: 1, presets: [(id: "user/old", name: "Old", brush: (size: 33.0))])"#,
        )
        .expect("write the old library");

        let library = UserLibrary::load_from(scratch.path()).expect("load");
        assert!(library.migrated());
        assert_eq!(library.presets().len(), 1);
        assert_eq!(library.get("user/old").unwrap().brush.size, 33.0);

        // Written into the new layout, so the next run does not migrate again…
        assert!(scratch.path().join(UserLibrary::FILE_NAME).exists());
        // …and the original is still there. A migration that deletes the only
        // copy of somebody's collection has to be right first time.
        assert!(scratch.legacy().exists());

        let again = UserLibrary::load_from(scratch.path()).expect("reload");
        assert!(!again.migrated(), "the second load must not migrate");
        assert_eq!(again.presets().len(), 1);
    }

    #[test]
    fn a_directory_that_already_has_brushes_ignores_the_old_file() {
        // The old file is left in place, so an older Umber can keep writing to
        // it. Reading it back over a newer library would undo everything done
        // since the move.
        let scratch = Scratch::new("no-remigrate");
        let mut library = UserLibrary::load_from(scratch.path()).expect("load");
        library
            .save(BrushPreset::unsaved("New", Brush::default()), None)
            .expect("save");
        fs::write(
            scratch.legacy(),
            r#"(version: 1, presets: [(id: "user/stale", name: "Stale", brush: ())])"#,
        )
        .expect("write a stale old library");

        let reloaded = UserLibrary::load_from(scratch.path()).expect("reload");
        assert!(!reloaded.migrated());
        assert_eq!(reloaded.presets().len(), 1);
        assert_eq!(reloaded.presets()[0].name, "New");
    }

    #[test]
    fn a_tip_that_will_not_decode_is_a_warning_rather_than_a_dead_library() {
        // One unreadable picture must not put the whole collection out of
        // reach — but it must not be silent either.
        let scratch = Scratch::new("bad-tip");
        let mut library = UserLibrary::load_from(scratch.path()).expect("load");
        library
            .save(BrushPreset::unsaved("Brush", Brush::default()), None)
            .expect("save");
        fs::create_dir_all(scratch.path().join("tips")).expect("tips");
        fs::write(scratch.tip_file("broken"), b"not a png").expect("write");

        let reloaded = UserLibrary::load_from(scratch.path()).expect("reload");
        assert_eq!(reloaded.presets().len(), 1);
        assert_eq!(reloaded.warnings().len(), 1, "{:?}", reloaded.warnings());
        assert!(reloaded.warnings()[0].contains("broken"));
    }

    #[test]
    fn slugs_are_safe_and_collapse_runs() {
        assert_eq!(slug("My Brush!!"), "my-brush");
        assert_eq!(slug("  spaced  out  "), "spaced-out");
        assert_eq!(slug("Ærø 12"), "r-12");
        assert_eq!(slug("!!!"), "");
    }
}
