//! The brush library: named, attributed presets, the set Umber ships with, and
//! the user's own set on disk.
//!
//! A preset is more than `{ name, brush }` because a library assembled from
//! several sources has to answer three questions the app cannot answer for
//! itself:
//!
//! - **Which brush is this?** — a stable [`BrushPreset::id`], so a saved
//!   selection survives a rename and so importing the same pack twice does not
//!   silently replace an edited copy.
//! - **Where did it come from?** — a [`Credit`], which is what makes shipping
//!   CC-BY material legal and CC0 material honest.
//! - **Where does it belong in the picker?** — a free-form
//!   [`BrushPreset::category`], because a flat list of two hundred brushes is
//!   not usable, and a [`BrushPreset::collection`] over the top of it for where
//!   the *user* has since decided it belongs.
//!
//! That last one has a second half, and it is the awkward one:
//! [`Library::collections`]. A user may file a **shipped** brush, and a shipped
//! preset lives in [`builtin`] — `include_str!`'d into the binary and replaced
//! wholesale by every update. So that choice cannot be written where the brush
//! is; it is recorded against the brush's stable id in the user's own
//! `brushes.ron`, which an update never touches.
//!
//! And a third half, for the collection with nothing in it yet:
//! [`Library::made_collections`]. Every collection Umber shows is otherwise
//! *derived* from some preset, so a collection somebody has just made — which
//! is the only state it can be in before a brush is dragged into it — has
//! nothing to be derived from and would not survive the next rebuild of the
//! merged list. It is written down instead, and [`UserLibrary::create_collection`]
//! is what makes one.
//!
//! Everything here is plain data: no GPU types, no file dialogs, no UI.

use std::collections::BTreeMap;
use std::fmt;
use std::fs;
use std::io;
use std::path::{Path, PathBuf};
use std::sync::{Arc, OnceLock};

use serde::{Deserialize, Serialize};

use crate::brush::Brush;
use crate::brushimport;
use crate::curve::ResponseCurve;
use crate::tip::TipMask;

/// The imported half of the shipped library, generated by
/// `cargo run -p umber-core --example build-brush-library`. Umber's own five
/// presets are in [`umber_defaults`] rather than in here, so the generator can
/// rewrite this file wholesale without a merge.
const BUILTIN_RON: &str = include_str!("../assets/builtin-brushes.ron");

/// The on-disk library format version. Bumped only when a change would make an
/// older Umber misread a newer file; additive fields do not need it, because
/// every field on [`Brush`] deserialises with a default.
const FORMAT_VERSION: u32 = 1;

/// Who made a preset and on what terms.
///
/// Present on everything Umber ships. CC0 material does not legally require it,
/// but recording it is how the licence stays checkable years later, when the
/// download script and its output have long since diverged.
#[derive(Clone, Debug, Default, PartialEq, Eq, Serialize, Deserialize)]
pub struct Credit {
    pub author: String,
    /// An SPDX identifier where one exists, e.g. `CC0-1.0`.
    pub licence: String,
    /// Where the original can be found.
    pub source: String,
}

/// A named brush the user can pick from the Brushes panel.
#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct BrushPreset {
    /// Stable and opaque. Umber's own are `umber/<slug>`, imports are
    /// `<pack>/<slug>`, and brushes the user saves are `user/<slug>`. Never
    /// derived from the current name at read time — renaming must not orphan a
    /// selection.
    pub id: String,
    pub name: String,
    /// Grouping for the picker. Free text rather than an enum: a brush pack
    /// brings its own categories, and Umber has no business enumerating them.
    #[serde(default)]
    pub category: String,
    /// The collection the *user* has put this brush in, which overrides
    /// [`Self::category`] wherever the two disagree.
    ///
    /// Two fields rather than one because they answer different questions and
    /// only one of them is the user's. `category` is what the brush arrived
    /// with — the pack's own grouping, or [`crate::style::classify`]'s reading
    /// of the name — and overwriting it would throw away the only thing that
    /// can file the brush if the user later takes their own choice off again.
    ///
    /// `None` is the ordinary state and costs nothing in the file, which is why
    /// adding it did not have to touch a line of the generated library.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub collection: Option<String>,
    #[serde(default)]
    pub credit: Option<Credit>,
    #[serde(default)]
    pub brush: Brush,
    /// The bitmap tip this brush stamps, named rather than carried.
    ///
    /// A [`crate::TipMask`] is a bitmap and the library is text, so the preset
    /// holds the *name* of a mask in the library's `tips/` directory and
    /// [`UserLibrary::tip`] resolves it. Naming rather than embedding is also
    /// what keeps two brushes cut from the same stamp sharing one file and one
    /// GPU upload.
    ///
    /// `None` is the procedural round dab, which is almost every brush — hence
    /// `skip_serializing_if`, so adding this field did not have to touch two
    /// hundred lines of the generated library.
    ///
    /// A name that resolves to nothing paints round. That is deliberate: a
    /// library copied to a machine without its tips should still give you the
    /// brush's size, spacing and dynamics rather than refusing to load.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub tip: Option<String>,
}

/// Where a brush read out of somebody else's file lands.
///
/// A collection rather than the style the name suggests, because the question
/// somebody has just after importing twenty brushes is "where did they go?",
/// and [`crate::style::classify`] answers it by scattering them across six
/// collections. The classifier's reading is not thrown away — it stays on
/// [`BrushPreset::category`] and is what the brush falls back to the moment the
/// user moves it out of here.
pub const IMPORTED: &str = "Imported";

impl BrushPreset {
    /// Which collection this brush belongs in: the user's choice where they
    /// have made one, and what the brush arrived with otherwise.
    pub fn collection(&self) -> &str {
        match self.collection.as_deref() {
            Some(name) if !name.is_empty() => name,
            _ => &self.category,
        }
    }

    /// A brush the user has just made in the brush editor and not yet saved.
    ///
    /// The id is left empty deliberately: [`UserLibrary::save`] allocates one
    /// that does not collide with anything already in the library, which it can
    /// only do once it knows which library the preset is going into.
    pub fn unsaved(name: impl Into<String>, brush: Brush) -> Self {
        Self {
            id: String::new(),
            name: name.into(),
            category: "My brushes".to_string(),
            collection: None,
            credit: None,
            brush,
            tip: None,
        }
    }
}

/// The library that ships inside the binary: Umber's own presets first, then
/// everything converted from the vendored packs.
///
/// Parsed once and leaked into a `OnceLock`, so the picker can hold a
/// `&'static` slice and redraw without re-parsing two hundred brushes a frame.
pub fn builtin() -> &'static [BrushPreset] {
    static LIBRARY: OnceLock<Vec<BrushPreset>> = OnceLock::new();
    LIBRARY.get_or_init(|| {
        let mut presets = umber_defaults();
        // The embedded file is generated and covered by a test in this module,
        // so a parse failure here is a build-time mistake, not a runtime
        // condition the app could recover from.
        presets.extend(
            parse_library(BUILTIN_RON)
                .expect("the embedded brush library is generated and tested; regenerate it"),
        );
        presets
    })
}

/// Umber's own presets, in Rust rather than in the generated file so that
/// regenerating the imported library cannot lose them.
///
/// Chosen to span the parameter space rather than to be exhaustive — a hard
/// edge, a soft edge, a dense wash and a sparse one — so the sliders' effects
/// are visible by comparison.
fn umber_defaults() -> Vec<BrushPreset> {
    let credit = Credit {
        author: "Umber contributors".to_string(),
        licence: "CC0-1.0".to_string(),
        source: "https://github.com/Spillebulle/umber".to_string(),
    };
    // Sorted by style like everything else, rather than into a collection of
    // their own. A taxonomy with one group that means "ours" is not a taxonomy;
    // the `umber/` id prefix is what marks these as the defaults, and the
    // browser shows the credit on every row.
    let make = |id: &str, name: &str, brush: Brush| BrushPreset {
        id: format!("umber/{id}"),
        name: name.to_string(),
        category: crate::style::classify(name, &brush).to_string(),
        collection: None,
        credit: Some(credit.clone()),
        brush,
        tip: None,
    };
    // A shipped brush that carries a bitmap tip, resolved out of
    // `crate::tip::builtin` rather than the user's library. Only one of *these*
    // — the generated library carries nineteen more, out of the three Krita
    // packs whose licences allow their masks to be redistributed — and this one
    // is Umber's own, drawn by `examples/build-bitmaps.rs`. Deliberately
    // sparse, because a stamp that paints the same under either coverage rule
    // would demonstrate nothing.
    let stamped = |id: &str, name: &str, tip: &str, brush: Brush| BrushPreset {
        tip: Some(tip.to_string()),
        ..make(id, name, brush)
    };
    vec![
        make(
            "soft-round",
            "Soft round",
            Brush {
                size: 40.0,
                hardness: 0.0,
                opacity: 0.85,
                spacing: 0.06,
                ..Brush::default()
            },
        ),
        make(
            "hard-round",
            "Hard round",
            Brush {
                size: 18.0,
                hardness: 1.0,
                opacity: 1.0,
                spacing: 0.08,
                ..Brush::default()
            },
        ),
        make(
            "ink",
            "Ink",
            Brush {
                size: 8.0,
                hardness: 0.9,
                opacity: 1.0,
                spacing: 0.04,
                stabilization: 0.6,
                min_size_ratio: 0.15,
                size_curve: ResponseCurve::EASE_IN,
                ..Brush::default()
            },
        ),
        make(
            "airbrush",
            "Airbrush",
            Brush {
                size: 90.0,
                hardness: 0.0,
                opacity: 0.18,
                spacing: 0.03,
                pressure_opacity: true,
                opacity_curve: ResponseCurve::EASE_IN,
                ..Brush::default()
            },
        ),
        make(
            "marker",
            "Marker",
            Brush {
                size: 28.0,
                hardness: 0.75,
                opacity: 0.6,
                spacing: 0.05,
                pressure_size: false,
                ..Brush::default()
            },
        ),
        stamped(
            "stipple-chalk",
            "Stipple chalk",
            "umber-stipple",
            Brush {
                size: 48.0,
                opacity: 0.9,
                // Close spacing: the stamp is a speckle, and it is the overlap
                // of many of them that makes a stroke rather than a row of
                // blobs.
                spacing: 0.06,
                pressure_size: false,
                pressure_opacity: true,
                // The stamp's brightest texel is around a half, so under a
                // `max` this brush would paint at half strength however hard it
                // was pressed. Measured, not assumed —
                // `a_shipped_stamp_paints_at_the_strength_it_was_drawn_at`.
                build_up: true,
                // Every stamp lands the same way up unless it is told not to,
                // and a repeated speckle that does is a texture with a grid in
                // it.
                dab_angle_jitter: 360.0,
                dab_ratio: 1.0,
                grain: 0.35,
                grain_scale: 180.0,
                grain_pattern: crate::brush::GrainPattern::Grit,
                ..Brush::default()
            },
        ),
    ]
}

/// The envelope the library is stored in. Private: the version is an
/// implementation detail of the file, not something a caller should hold.
#[derive(Serialize, Deserialize)]
struct LibraryFile {
    version: u32,
    presets: Vec<BrushPreset>,
    /// Collections the user has put brushes this file does *not* hold into,
    /// by [`BrushPreset::id`]. See [`Library::collections`].
    ///
    /// Skipped when empty, so a library nobody has re-grouped — and the whole
    /// of the generated shipped one — is written exactly as it was before this
    /// existed.
    #[serde(default, skip_serializing_if = "BTreeMap::is_empty")]
    collections: BTreeMap<String, String>,
    /// Collections the user made, which no brush need be in. See
    /// [`Library::made_collections`].
    ///
    /// `#[serde(default)]` and skipped when empty, so a `brushes.ron` written
    /// before this existed still loads and a library nobody has added a
    /// collection to is written byte for byte as it was. That is why
    /// [`FORMAT_VERSION`] did not move: an older Umber reading a newer file
    /// ignores the field and opens the brushes, which is the same rule the dock
    /// config lives by.
    #[serde(default, skip_serializing_if = "Vec::is_empty")]
    made_collections: Vec<String>,
}

/// Everything in a library file.
///
/// The presets, and two things that are not presets: where the user has filed
/// brushes that are *not in this file* ([`Library::collections`]), and the
/// collections they made that no brush is in yet
/// ([`Library::made_collections`]). Both exist because a collection is
/// otherwise derived from a preset, and neither of those has one to be derived
/// from.
#[derive(Clone, Debug, Default)]
pub struct Library {
    pub presets: Vec<BrushPreset>,
    /// Preset id to collection name, for ids this library does not hold.
    ///
    /// This is where a user's re-grouping of a **shipped** brush lives, and it
    /// has to be a table beside the presets rather than a field on one because
    /// there is no shipped preset to write to: [`builtin`] is `include_str!`'d
    /// into the binary and replaced wholesale by every update. A choice
    /// recorded there would last until the next release and then vanish, which
    /// is the worst way for a preference to be lost — silently, months later.
    ///
    /// Recorded here it survives an update twice over: the file is in the
    /// user's own data directory, which an update never touches, and it names
    /// the brush by its **stable id**, so a release that adds, removes or
    /// reorders shipped brushes still resolves it to the same one.
    ///
    /// An entry whose id no longer names anything is kept rather than swept.
    /// The shipped library is not this module's to enumerate — only the app
    /// knows what is in it this release — and a brush that has gone might come
    /// back.
    pub collections: BTreeMap<String, String>,
    /// Collections the user has made, in the order they made them.
    ///
    /// Every *other* collection Umber shows is derived: it exists because some
    /// preset's [`BrushPreset::collection`] or [`BrushPreset::category`] names
    /// it. A collection somebody has just made has no members yet, so there is
    /// nothing to derive it from — and if it were not written down it would
    /// vanish the moment the merged preset list was rebuilt, which happens on
    /// every save, delete, import and move. Hence a list of its own.
    ///
    /// A name stays here once it is in. Dragging the last brush out of a
    /// collection the user made is not the same act as unmaking it, and a
    /// collection that disappeared from under a drag would take the drop target
    /// with it.
    pub made_collections: Vec<String>,
}

/// What came of asking for a new collection.
///
/// Three answers rather than a `bool`, because the two refusals need different
/// sentences: a name already in use is a collection the user can go and use,
/// and an empty one is a field they have not finished filling in.
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub enum NewCollection {
    Created,
    /// A collection of that name is already there — the one that was asked for,
    /// found rather than made a second time.
    Exists,
    /// Nothing but whitespace.
    Unnamed,
}

/// Whether two collection names are the same collection.
///
/// Trimmed and case-folded, because "my brushes" typed into the field and "My
/// brushes" already on the rail are one collection to everybody except a byte
/// comparison — and two rows with the same name are two places to drag a brush
/// into and one place to look for it afterwards.
///
/// ASCII-only folding, which suits the data for the same reason the browser's
/// search folds that way: the non-ASCII in a collection name is the same bytes
/// in either case and matches regardless.
pub fn same_collection(a: &str, b: &str) -> bool {
    a.trim().eq_ignore_ascii_case(b.trim())
}

/// Read a RON brush library, presets and all.
pub fn parse(text: &str) -> Result<Library, PresetError> {
    let file: LibraryFile =
        ron::from_str(text).map_err(|e| PresetError::Malformed(None, e.to_string()))?;
    if file.version > FORMAT_VERSION {
        return Err(PresetError::UnsupportedVersion(None, file.version));
    }
    Ok(Library {
        presets: file.presets,
        collections: file.collections,
        made_collections: file.made_collections,
    })
}

/// Read a RON brush library.
///
/// The presets alone, for the two callers — the `.ron` importer and the library
/// generator — that read somebody's file for the brushes in it and have no use
/// for where its owner filed brushes of their own.
pub fn parse_library(text: &str) -> Result<Vec<BrushPreset>, PresetError> {
    Ok(parse(text)?.presets)
}

/// Serialise a brush library to RON, pretty-printed so that a generated library
/// gives a readable diff when it is regenerated.
pub fn to_ron(presets: &[BrushPreset]) -> Result<String, PresetError> {
    to_ron_file(presets, &BTreeMap::new(), &[])
}

fn to_ron_file(
    presets: &[BrushPreset],
    collections: &BTreeMap<String, String>,
    made_collections: &[String],
) -> Result<String, PresetError> {
    let file = LibraryFile {
        version: FORMAT_VERSION,
        presets: presets.to_vec(),
        collections: collections.clone(),
        made_collections: made_collections.to_vec(),
    };
    let config = ron::ser::PrettyConfig::new().struct_names(false);
    ron::ser::to_string_pretty(&file, config)
        .map_err(|e| PresetError::Malformed(None, e.to_string()))
}

/// The user's own brushes: everything saved out of the brush editor, plus
/// anything imported from a file.
///
/// Kept entirely separate from [`builtin`]: the shipped library is read-only and
/// is replaced wholesale by an update, so writing user brushes into it would
/// lose them.
///
/// # Why a directory
///
/// This used to be a single `brushes.ron`. A bitmap tip does not go in a text
/// file, so the library is now a directory:
///
/// ```text
/// brushes/
///     brushes.ron     the presets, exactly the format it always was
///     tips/
///         <name>.png  one 8-bit greyscale coverage mask per tip
/// ```
///
/// A directory rather than a zip, which was the obvious alternative. Three
/// reasons, in order of weight:
///
/// - **A write touches only what changed.** Renaming a brush rewrites a few
///   kilobytes of RON; in a zip it rewrites the archive, tips and all. The
///   library is written on *every* edit, so that is the common case, not the
///   rare one.
/// - **The atomic-rename trick keeps working.** `write` puts
///   the RON beside itself and renames over the old one, so an interrupted
///   write cannot leave a truncated collection. Doing that for a whole zip
///   would mean rewriting and re-fsyncing every mask to change a name, and an
///   interrupted write would then be risking the tips as well.
/// - **The tips are ordinary files.** A stamp brush's content is a picture;
///   being able to open, replace or copy one with anything that opens a picture
///   is worth more than tidiness.
///
/// The old flat `brushes.ron` is migrated rather than ignored — see
/// [`UserLibrary::load_from`].
#[derive(Clone, Debug)]
pub struct UserLibrary {
    dir: PathBuf,
    presets: Vec<BrushPreset>,
    /// Where the user has filed brushes this library does not hold — the
    /// shipped ones. See [`Library::collections`], which is the argument for
    /// why this cannot live on the preset.
    collections: BTreeMap<String, String>,
    /// Collections the user made. See [`Library::made_collections`].
    made_collections: Vec<String>,
    /// Every mask in `tips/`, by name.
    ///
    /// `Arc` because the same mask is handed to the editor, then to the GPU,
    /// and identity is what lets the renderer skip re-uploading it at the start
    /// of every stroke.
    tips: BTreeMap<String, Arc<TipMask>>,
    migrated: bool,
    warnings: Vec<String>,
}

impl UserLibrary {
    /// Directory name under the platform's user-data directory, and the name of
    /// the presets file inside it. They match on purpose: the directory
    /// replaced a file of that name, so finding the old one is
    /// `dir.with_extension("ron")` and nothing more.
    pub const DIR_NAME: &'static str = "brushes";
    pub const FILE_NAME: &'static str = "brushes.ron";
    const TIPS_DIR: &'static str = "tips";

    /// Where [`UserLibrary::load`] reads from: `%APPDATA%\Umber\data\brushes`
    /// on Windows, `~/.local/share/umber/brushes` on Linux,
    /// `~/Library/Application Support/Umber/brushes` on macOS. `None` on a
    /// system with no home directory.
    pub fn default_dir() -> Option<PathBuf> {
        directories::ProjectDirs::from("", "", "Umber")
            .map(|dirs| dirs.data_dir().join(Self::DIR_NAME))
    }

    /// Load the user's library from the default location.
    ///
    /// A missing directory is an empty library, not an error — that is the
    /// state every user starts in.
    pub fn load() -> Result<Self, PresetError> {
        let dir = Self::default_dir().ok_or(PresetError::NoDataDirectory)?;
        Self::load_from(dir)
    }

    /// Load from an explicit directory. Used by the tests, and by anyone who
    /// wants a second library (a project-local brush set, say).
    ///
    /// If the directory holds no `brushes.ron` but a flat one sits beside it —
    /// `…/data/brushes.ron`, where every library written before tips existed
    /// lives — that file is read and written into the new layout. The original
    /// is **left where it is**: a migration that deletes the only copy of the
    /// user's collection has to be right first time, and this one does not have
    /// to be. An older Umber on the same machine also keeps working, at the
    /// price of the two diverging, which is the better half of that trade.
    pub fn load_from(dir: impl Into<PathBuf>) -> Result<Self, PresetError> {
        let dir = dir.into();
        let file = dir.join(Self::FILE_NAME);
        let mut migrated = false;

        let text = match read_if_present(&file)? {
            Some(text) => Some(text),
            None => match read_if_present(&Self::legacy_file(&dir))? {
                Some(text) => {
                    migrated = true;
                    Some(text)
                }
                None => None,
            },
        };
        let contents = match &text {
            Some(text) => parse(text).map_err(|e| e.at(&file))?,
            None => Library::default(),
        };

        let mut library = Self {
            dir,
            presets: contents.presets,
            collections: contents.collections,
            made_collections: contents.made_collections,
            tips: BTreeMap::new(),
            migrated,
            warnings: Vec::new(),
        };
        library.load_tips();
        // Only after the tips are in hand: the migrated file may name tips that
        // were never there, and `write` is what drops those references.
        //
        // A migration that cannot be written is a warning rather than a failed
        // load. The presets are already in memory and the original file has not
        // been touched, so carrying on costs nothing and refusing would put the
        // user's whole collection out of reach over a directory that could not
        // be created. `migrated` stays true, so the next run tries again.
        if migrated && let Err(e) = library.write() {
            library.warnings.push(e.to_string());
        }
        Ok(library)
    }

    /// The flat `brushes.ron` this directory replaced.
    fn legacy_file(dir: &Path) -> PathBuf {
        dir.with_extension("ron")
    }

    fn tips_dir(&self) -> PathBuf {
        self.dir.join(Self::TIPS_DIR)
    }

    /// Read every mask in `tips/`.
    ///
    /// A mask that will not decode is skipped with a warning rather than
    /// failing the load: one unreadable picture must not put the whole
    /// collection out of reach, and the brush that named it still paints — as a
    /// round one. The warning is what stops that being silent.
    fn load_tips(&mut self) {
        let Ok(entries) = fs::read_dir(self.tips_dir()) else {
            return;
        };
        for entry in entries.flatten() {
            let path = entry.path();
            if !path
                .extension()
                .is_some_and(|e| e.eq_ignore_ascii_case("png"))
            {
                continue;
            }
            let Some(name) = path.file_stem().map(|s| s.to_string_lossy().into_owned()) else {
                continue;
            };
            match fs::read(&path).map_err(|source| PresetError::Io {
                path: path.clone(),
                source,
            }) {
                Ok(bytes) => match TipMask::from_png(&bytes) {
                    Ok(mask) => {
                        self.tips.insert(name, Arc::new(mask));
                    }
                    Err(e) => self.warnings.push(format!("{}: {e}", path.display())),
                },
                Err(e) => self.warnings.push(e.to_string()),
            }
        }
    }

    /// The library's directory. Shown to the user, so it names the folder they
    /// would open rather than the RON inside it.
    pub fn dir(&self) -> &Path {
        &self.dir
    }

    /// True when this load moved a pre-tips `brushes.ron` into the directory.
    /// Worth telling the user once: their brushes are somewhere else now.
    pub fn migrated(&self) -> bool {
        self.migrated
    }

    /// Anything that could not be read but did not stop the library loading.
    pub fn warnings(&self) -> &[String] {
        &self.warnings
    }

    /// Everything saved, in the order it was added.
    pub fn presets(&self) -> &[BrushPreset] {
        &self.presets
    }

    pub fn get(&self, id: &str) -> Option<&BrushPreset> {
        self.presets.iter().find(|p| p.id == id)
    }

    /// The mask a [`BrushPreset::tip`] names, if it is here.
    pub fn tip(&self, name: &str) -> Option<&Arc<TipMask>> {
        self.tips.get(name)
    }

    /// Every mask, by name. The editor keeps its own map of these so that
    /// selecting a brush does not have to reach for the library.
    pub fn tips(&self) -> &BTreeMap<String, Arc<TipMask>> {
        &self.tips
    }

    /// Add `preset`, or replace the one that already has its id, then write the
    /// library out. Returns the id, which the caller needs when the preset
    /// arrived from [`BrushPreset::unsaved`] and had none.
    ///
    /// `tip` **replaces** the preset's bitmap tip. `None` leaves
    /// [`BrushPreset::tip`] naming whatever it already named — which is what
    /// makes "Update" on a stamp brush keep its stamp — so taking a tip off is
    /// clearing that field, not passing `None` here.
    pub fn save(
        &mut self,
        mut preset: BrushPreset,
        tip: Option<TipMask>,
    ) -> Result<String, PresetError> {
        if preset.id.is_empty() {
            preset.id = self.allocate_id(&preset.name);
        }
        if let Some(mask) = tip {
            preset.tip = Some(self.store_tip(&preset.id, mask)?);
        }
        let id = preset.id.clone();
        match self.presets.iter_mut().find(|p| p.id == id) {
            Some(existing) => *existing = preset,
            None => self.presets.push(preset),
        }
        self.write()?;
        Ok(id)
    }

    /// Remove a brush. `false` means there was nothing with that id, which is
    /// not an error — a double-click on Delete should not raise a dialog.
    pub fn delete(&mut self, id: &str) -> Result<bool, PresetError> {
        let before = self.presets.len();
        self.presets.retain(|p| p.id != id);
        if self.presets.len() == before {
            return Ok(false);
        }
        self.write()?;
        Ok(true)
    }

    /// Put a brush in a collection, or take the user's choice back off with
    /// `None`.
    ///
    /// `id` may name a brush this library does not hold. That is not an error
    /// and it is the whole reason the two halves below exist: the brush is a
    /// shipped one, [`builtin`] is compiled into the binary and replaced
    /// wholesale by every update, so there is nowhere on the preset to write
    /// the choice down. It goes in a table beside the presets instead, against
    /// the brush's stable id, in the user's own data directory — see
    /// [`Library::collections`].
    ///
    /// A brush the library *does* hold carries its own collection on the preset
    /// rather than in that table, so the choice travels with the brush into an
    /// export and comes back with it on another machine.
    pub fn assign(&mut self, id: &str, collection: Option<&str>) -> Result<(), PresetError> {
        let collection = collection.map(str::trim).filter(|name| !name.is_empty());
        match self.presets.iter_mut().find(|preset| preset.id == id) {
            Some(preset) => {
                preset.collection = collection.map(ToOwned::to_owned);
                // Belt and braces: an id that was in the table before this
                // library came to hold a preset of that name would otherwise
                // outvote the field, and the two would disagree for ever.
                self.collections.remove(id);
            }
            None => match collection {
                Some(name) => {
                    self.collections.insert(id.to_owned(), name.to_owned());
                }
                None => {
                    self.collections.remove(id);
                }
            },
        }
        self.write()
    }

    /// Stamp the recorded collections onto presets from elsewhere.
    ///
    /// The caller passes the whole merged library — everything shipped, then
    /// everything here — and gets back the shipped half filed where the user
    /// put it. Nothing this library holds is touched by the table, so the two
    /// cannot disagree.
    ///
    /// An empty table is the ordinary case and costs one branch.
    pub fn apply_collections(&self, presets: &mut [BrushPreset]) {
        if self.collections.is_empty() {
            return;
        }
        for preset in presets {
            if let Some(name) = self.collections.get(&preset.id) {
                preset.collection = Some(name.clone());
            }
        }
    }

    /// Where the user has filed brushes this library does not hold.
    pub fn collections(&self) -> &BTreeMap<String, String> {
        &self.collections
    }

    /// The collections the user has made, in the order they made them.
    ///
    /// The caller adds these to whatever the presets derive, so a collection
    /// with nothing in it yet is still a row on the rail and still a thing a
    /// brush can be dragged onto. See [`Library::made_collections`].
    pub fn made_collections(&self) -> &[String] {
        &self.made_collections
    }

    /// Make an empty collection.
    ///
    /// `existing` is every collection name already on screen, and it has to
    /// come from the caller: collections are *derived* from the merged preset
    /// list, and the shipped half of that list is not this module's to
    /// enumerate — [`builtin`] is compiled into the binary and only the app
    /// knows what is in it this release. [`IMPORTED`] is added to whatever is
    /// passed, because an import can create that collection at any moment and a
    /// name that would collide with it the first time somebody imports a brush
    /// is a name to refuse now rather than later.
    ///
    /// A name already in use is [`NewCollection::Exists`] rather than a second
    /// row of the same name — the collection the user asked for is already
    /// there, so the honest outcome is to send them to it. Comparison is
    /// [`same_collection`]'s, so case and surrounding space do not make a
    /// second one.
    ///
    /// Nothing is written unless a collection was actually made.
    pub fn create_collection(
        &mut self,
        name: &str,
        existing: &[String],
    ) -> Result<NewCollection, PresetError> {
        let name = name.trim();
        if name.is_empty() {
            return Ok(NewCollection::Unnamed);
        }
        let taken = existing
            .iter()
            .map(String::as_str)
            .chain(self.made_collections.iter().map(String::as_str))
            .chain(self.presets.iter().map(BrushPreset::collection))
            .chain(std::iter::once(IMPORTED))
            .any(|other| same_collection(other, name));
        if taken {
            return Ok(NewCollection::Exists);
        }
        self.made_collections.push(name.to_owned());
        self.write()?;
        Ok(NewCollection::Created)
    }

    /// Change a brush's display name. The id deliberately does not follow, so
    /// anything holding a selection keeps it.
    pub fn rename(&mut self, id: &str, name: impl Into<String>) -> Result<bool, PresetError> {
        let Some(preset) = self.presets.iter_mut().find(|p| p.id == id) else {
            return Ok(false);
        };
        preset.name = name.into();
        self.write()?;
        Ok(true)
    }

    /// Read a brush file from anywhere on disk, add everything in it to the
    /// library, and return what was added.
    ///
    /// One file can hold many brushes (an Umber `.ron` library), so this returns
    /// a `Vec` rather than a single preset.
    pub fn import_file(&mut self, path: &Path) -> Result<Vec<BrushPreset>, PresetError> {
        let found = brushimport::read_file(path)?;
        let mut added = Vec::with_capacity(found.len());
        // `dropped` is deliberately not consulted here: the library keeps what
        // the reader could make of a file, and saying what did not survive is
        // the caller's job — it has the whole selection in hand and can report
        // twenty files as one sentence.
        for brushimport::Imported {
            mut preset, tip, ..
        } in found
        {
            // Importing the same pack twice must not overwrite a copy the user
            // has since edited, so a colliding id is reallocated rather than
            // replaced. This is the one place ids are not stable across a
            // round trip, and it is the safe direction to be unstable in.
            if preset.id.is_empty() || self.presets.iter().any(|p| p.id == preset.id) {
                preset.id = self.allocate_id(&preset.name);
            }
            // Everything read out of somebody else's file lands in one
            // collection, so that "where did those twenty brushes go?" has an
            // answer that is not "somewhere among two hundred and thirty-nine".
            // The style each brush was classified as is still on `category`
            // underneath, and is what it falls back to when it is moved out.
            //
            // `get_or_insert` rather than an assignment: a preset that already
            // names a collection came out of an Umber `.ron`, which means it is
            // the user's own export coming home, and their grouping is not this
            // function's to overwrite.
            preset
                .collection
                .get_or_insert_with(|| IMPORTED.to_string());
            match tip {
                Some(mask) => preset.tip = Some(self.store_tip(&preset.id, mask)?),
                // An Umber `.ron` names its tips, and the files are not in it —
                // the exported library is text. Rather than leave a reference
                // pointing at nothing, drop it unless this library happens to
                // hold a mask by that name already, which is the case where the
                // user is re-importing their own export.
                None => {
                    if preset
                        .tip
                        .as_deref()
                        .is_some_and(|n| !self.tips.contains_key(n))
                    {
                        preset.tip = None;
                    }
                }
            }
            self.presets.push(preset.clone());
            added.push(preset);
        }
        self.write()?;
        Ok(added)
    }

    /// Write a mask into `tips/` and return the name to record on the preset.
    ///
    /// Named after the preset that first used it rather than after its contents:
    /// a hash would deduplicate identical masks, but it would also make the
    /// directory unreadable, and a stamp library is something people go and look
    /// at.
    fn store_tip(&mut self, preset_id: &str, mask: TipMask) -> Result<String, PresetError> {
        let name = self.allocate_tip_name(preset_id);
        create_dir(&self.tips_dir())?;
        let path = self.tips_dir().join(format!("{name}.png"));
        fs::write(&path, mask.to_png()?).map_err(|source| PresetError::Io {
            path: path.clone(),
            source,
        })?;
        self.tips.insert(name.clone(), Arc::new(mask));
        Ok(name)
    }

    fn allocate_id(&self, name: &str) -> String {
        let stem = slug(name);
        let stem = if stem.is_empty() { "brush" } else { &stem };
        let mut candidate = format!("user/{stem}");
        let mut n = 2;
        while self.presets.iter().any(|p| p.id == candidate) {
            candidate = format!("user/{stem}-{n}");
            n += 1;
        }
        candidate
    }

    /// A file name for a tip. Ids carry a `/`, which a file name cannot, so
    /// they go through [`slug`] — and two ids can slug to the same thing, so
    /// the result still has to be made unique.
    fn allocate_tip_name(&self, preset_id: &str) -> String {
        let stem = slug(preset_id);
        let stem = if stem.is_empty() { "tip" } else { &stem };
        let mut candidate = stem.to_string();
        let mut n = 2;
        while self.tips.contains_key(&candidate) {
            candidate = format!("{stem}-{n}");
            n += 1;
        }
        candidate
    }

    fn write(&mut self) -> Result<(), PresetError> {
        create_dir(&self.dir)?;
        let text = to_ron_file(&self.presets, &self.collections, &self.made_collections)?;
        let file = self.dir.join(Self::FILE_NAME);

        // Write beside the library and rename over it. A direct write that is
        // interrupted — a full disk, a crash, a laptop lid — leaves a truncated
        // file, and the user's whole brush collection with it; a rename is
        // atomic enough on every platform Umber runs on that the old file
        // survives instead.
        let tmp = file.with_extension("ron.tmp");
        fs::write(&tmp, text).map_err(|source| PresetError::Io {
            path: tmp.clone(),
            source,
        })?;
        fs::rename(&tmp, &file).map_err(|source| PresetError::Io {
            path: file.clone(),
            source,
        })?;

        self.prune_tips();
        Ok(())
    }

    /// Delete the masks no preset names any more.
    ///
    /// Deleting a stamp brush has to take its picture with it, or the directory
    /// grows a megabyte per discarded experiment and never gives it back. Run
    /// *after* the RON is safely written, so a failure here leaves orphaned
    /// files rather than a preset pointing at a file that has gone.
    fn prune_tips(&mut self) {
        let referenced: Vec<&str> = self
            .presets
            .iter()
            .filter_map(|preset| preset.tip.as_deref())
            .collect();
        let orphans: Vec<String> = self
            .tips
            .keys()
            .filter(|name| !referenced.contains(&name.as_str()))
            .cloned()
            .collect();
        for name in orphans {
            // Best effort: a mask that will not delete is a file left behind,
            // which is untidy, and nothing worse.
            let _ = fs::remove_file(self.tips_dir().join(format!("{name}.png")));
            self.tips.remove(&name);
        }
    }
}

fn create_dir(dir: &PathBuf) -> Result<(), PresetError> {
    if dir.as_os_str().is_empty() {
        return Ok(());
    }
    fs::create_dir_all(dir).map_err(|source| PresetError::Io {
        path: dir.clone(),
        source,
    })
}

/// Read a file, treating "not there" as `None` rather than as a failure.
fn read_if_present(path: &Path) -> Result<Option<String>, PresetError> {
    match fs::read_to_string(path) {
        Ok(text) => Ok(Some(text)),
        Err(e) if e.kind() == io::ErrorKind::NotFound => Ok(None),
        Err(source) => Err(PresetError::Io {
            path: path.to_path_buf(),
            source,
        }),
    }
}

/// Lowercase, hyphen-separated, ASCII-only. Ids end up in file paths and RON
/// strings, so anything exotic is flattened rather than escaped.
///
/// Public because the importers and the library generator all have to produce
/// ids the same way; two slug functions that disagree would be two id schemes.
pub fn slug(name: &str) -> String {
    let mut out = String::with_capacity(name.len());
    for c in name.chars() {
        if c.is_ascii_alphanumeric() {
            out.push(c.to_ascii_lowercase());
        } else if !out.ends_with('-') {
            out.push('-');
        }
    }
    out.trim_matches('-').to_string()
}

/// Anything that can go wrong reading or writing brushes.
#[derive(Debug)]
pub enum PresetError {
    /// The platform reported no user-data directory. Rare, and not something
    /// the app can fix — but it must not be a panic either.
    NoDataDirectory,
    Io {
        path: PathBuf,
        source: io::Error,
    },
    /// The file is the right kind but does not parse.
    Malformed(Option<PathBuf>, String),
    /// A library written by a newer Umber.
    UnsupportedVersion(Option<PathBuf>, u32),
    /// An extension no importer claims.
    UnknownFormat(PathBuf),
}

impl PresetError {
    /// Attach the file an error came from. Parsers work on text and cannot know
    /// the path; the code that opened the file fills it in on the way out.
    pub(crate) fn at(self, path: &Path) -> Self {
        match self {
            Self::Malformed(None, message) => Self::Malformed(Some(path.to_path_buf()), message),
            Self::UnsupportedVersion(None, v) => {
                Self::UnsupportedVersion(Some(path.to_path_buf()), v)
            }
            other => other,
        }
    }
}

impl fmt::Display for PresetError {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        fn where_(path: &Option<PathBuf>) -> String {
            match path {
                Some(p) => format!(" in {}", p.display()),
                None => String::new(),
            }
        }
        match self {
            Self::NoDataDirectory => f.write_str("this system has no user data directory"),
            Self::Io { path, source } => write!(f, "{}: {source}", path.display()),
            Self::Malformed(path, message) => {
                write!(f, "could not read the brushes{}: {message}", where_(path))
            }
            Self::UnsupportedVersion(path, v) => write!(
                f,
                "brush library version {v}{} is newer than this build of Umber understands",
                where_(path)
            ),
            Self::UnknownFormat(path) => write!(
                f,
                "{} is not a brush file Umber can read",
                path.file_name()
                    .unwrap_or(path.as_os_str())
                    .to_string_lossy()
            ),
        }
    }
}

impl std::error::Error for PresetError {
    fn source(&self) -> Option<&(dyn std::error::Error + 'static)> {
        match self {
            Self::Io { source, .. } => Some(source),
            _ => None,
        }
    }
}

/// Used by [`UserLibrary::load_from`] and by the importers, both of which get a
/// path from the caller.
pub(crate) fn read_to_string(path: &Path) -> Result<String, PresetError> {
    fs::read_to_string(path).map_err(|source| PresetError::Io {
        path: path.to_path_buf(),
        source,
    })
}

/// The same, for the formats that are not text — `.gbr` is a header and a
/// bitmap.
pub(crate) fn read_bytes(path: &Path) -> Result<Vec<u8>, PresetError> {
    fs::read(path).map_err(|source| PresetError::Io {
        path: path.to_path_buf(),
        source,
    })
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::brush::BrushMode;

    /// A scratch data directory in the OS temp directory, removed on drop, so
    /// the tests never touch the developer's real brush collection.
    ///
    /// [`Scratch::path`] is the *library directory* inside it, leaving room
    /// beside it for the flat `brushes.ron` the migration reads.
    struct Scratch(PathBuf);

    impl Scratch {
        fn new(tag: &str) -> Self {
            let dir = std::env::temp_dir()
                .join(format!("umber-preset-test-{tag}-{}", std::process::id()));
            let _ = fs::remove_dir_all(&dir);
            Self(dir)
        }

        fn path(&self) -> PathBuf {
            self.0.join(UserLibrary::DIR_NAME)
        }

        /// Where a library written before tips existed sits.
        fn legacy(&self) -> PathBuf {
            self.0.join(UserLibrary::FILE_NAME)
        }

        fn tip_file(&self, name: &str) -> PathBuf {
            self.path().join("tips").join(format!("{name}.png"))
        }
    }

    impl Drop for Scratch {
        fn drop(&mut self) {
            let _ = fs::remove_dir_all(&self.0);
        }
    }

    #[test]
    fn the_embedded_library_parses_and_is_not_empty() {
        let library = builtin();
        assert!(
            library.len() > umber_defaults().len(),
            "the generated library added nothing; regenerate it"
        );
    }

    #[test]
    fn every_shipped_preset_is_usable_and_attributed() {
        for preset in builtin() {
            let b = &preset.brush;
            assert!(
                (Brush::MIN_SIZE..=Brush::MAX_SIZE).contains(&b.size),
                "{} has an out-of-range size: {}",
                preset.name,
                b.size
            );
            assert!(
                b.step_at(0.0) > 0.0,
                "{} would spin the dab loop",
                preset.name
            );
            assert!((0.0..=1.0).contains(&b.opacity), "{} opacity", preset.name);
            assert!(
                (0.0..=1.0).contains(&b.hardness),
                "{} hardness",
                preset.name
            );
            assert!(
                b.stabilization < 1.0,
                "{} would never reach the pointer",
                preset.name
            );
            // Shipping something whose licence we cannot name is exactly the
            // mistake this field exists to prevent.
            let credit = preset
                .credit
                .as_ref()
                .unwrap_or_else(|| panic!("{} ships with no credit", preset.name));
            assert!(!credit.licence.is_empty(), "{} has no licence", preset.name);
        }
    }

    #[test]
    fn shipped_ids_are_unique() {
        // Two presets sharing an id would make a saved selection ambiguous.
        let mut ids: Vec<&str> = builtin().iter().map(|p| p.id.as_str()).collect();
        ids.sort_unstable();
        let before = ids.len();
        ids.dedup();
        assert_eq!(before, ids.len(), "duplicate preset ids in the library");
    }

    #[test]
    fn a_library_survives_a_round_trip() {
        let text = to_ron(builtin()).expect("serialise");
        let back = parse_library(&text).expect("parse");
        assert_eq!(back, builtin());
    }

    #[test]
    fn a_partial_preset_fills_in_brush_defaults() {
        // The point of `#[serde(default)]` on `Brush`: a hand-written library
        // should not have to name eleven parameters to change one.
        let text = r#"(version: 1, presets: [(id: "t/x", name: "X", brush: (size: 12.0))])"#;
        let presets = parse_library(text).expect("parse");
        assert_eq!(presets[0].brush.size, 12.0);
        assert_eq!(presets[0].brush.spacing, Brush::default().spacing);
    }

    #[test]
    fn a_newer_library_is_refused_rather_than_misread() {
        let text = r#"(version: 99, presets: [])"#;
        assert!(matches!(
            parse_library(text),
            Err(PresetError::UnsupportedVersion(_, 99))
        ));
    }

    #[test]
    fn a_missing_user_library_loads_as_empty() {
        let scratch = Scratch::new("missing");
        let library = UserLibrary::load_from(scratch.path()).expect("load");
        assert!(library.presets().is_empty());
    }

    #[test]
    fn saving_then_reloading_keeps_the_brush() {
        let scratch = Scratch::new("save");
        let mut library = UserLibrary::load_from(scratch.path()).expect("load");
        let id = library
            .save(
                BrushPreset::unsaved(
                    "My liner",
                    Brush {
                        size: 7.0,
                        mode: BrushMode::Erase,
                        ..Brush::default()
                    },
                ),
                None,
            )
            .expect("save");
        assert_eq!(id, "user/my-liner");

        let reloaded = UserLibrary::load_from(scratch.path()).expect("reload");
        let preset = reloaded.get(&id).expect("saved brush is there");
        assert_eq!(preset.name, "My liner");
        assert_eq!(preset.brush.size, 7.0);
        assert_eq!(preset.brush.mode, BrushMode::Erase);
    }

    /// The modulation table is a fixed array behind a hand-written
    /// `Serialize`/`Deserialize` pair, so it writes only its live entries. Both
    /// halves need a round trip: the empty case, which must cost `[]` rather
    /// than twelve inert rows in every one of 239 presets, and a filled one,
    /// which must come back identical.
    #[test]
    fn a_modulated_brush_survives_the_library() {
        use crate::dynamics::{DabInput, DabTarget, Modulation, Modulations};

        let scratch = Scratch::new("modulated");
        let mut library = UserLibrary::load_from(scratch.path()).expect("load");
        let modulations: Modulations = [
            Modulation {
                target: DabTarget::Ratio,
                input: DabInput::Random,
                low: -1.5,
                high: 1.5,
                curve: ResponseCurve::EASE_IN,
            },
            Modulation {
                target: DabTarget::Size,
                input: DabInput::Speed,
                low: 0.0,
                high: -0.6,
                curve: ResponseCurve::LINEAR,
            },
        ]
        .into_iter()
        .collect();

        let id = library
            .save(
                BrushPreset::unsaved(
                    "Flick",
                    Brush {
                        modulations,
                        ..Brush::default()
                    },
                ),
                None,
            )
            .expect("save");

        let text = std::fs::read_to_string(scratch.path().join("brushes.ron")).expect("read");
        assert!(text.contains("Random"), "the table was not written: {text}");

        let reloaded = UserLibrary::load_from(scratch.path()).expect("reload");
        let back = reloaded.get(&id).expect("saved brush is there");
        assert_eq!(back.brush.modulations, modulations);
    }

    /// A library written before the table existed names none of its fields and
    /// has to load with an empty one rather than failing.
    #[test]
    fn a_library_from_before_the_modulation_table_still_loads() {
        let old = r#"(
            version: 1,
            presets: [(
                id: "user/old",
                name: "Old",
                category: "Inks & pens",
                brush: (size: 12.0),
            )],
        )"#;
        let presets = parse_library(old).expect("an older library still parses");
        assert_eq!(presets[0].brush.size, 12.0);
        assert!(presets[0].brush.modulations.is_empty());
        // And the fields added alongside it take their defaults rather than
        // zero, which for the stroke ramp would be a division by nothing.
        assert_eq!(presets[0].brush.stroke_span, Brush::default().stroke_span);
        assert_eq!(presets[0].brush.speed_offset, 0.0);
    }

    /// The user's own grouping is theirs, so it has to reach the file and come
    /// back. `category` underneath it is untouched — that is what the brush
    /// falls back to if the choice is ever taken off again.
    #[test]
    fn a_collection_the_user_chose_survives_the_file() {
        let scratch = Scratch::new("collection");
        let mut library = UserLibrary::load_from(scratch.path()).expect("load");
        let id = library
            .save(
                BrushPreset {
                    category: "Inks & pens".to_string(),
                    collection: Some("Comics".to_string()),
                    ..BrushPreset::unsaved("Nib", Brush::default())
                },
                None,
            )
            .expect("save");

        let text = std::fs::read_to_string(scratch.path().join("brushes.ron")).expect("read");
        assert!(
            text.contains("Comics"),
            "the collection was not written: {text}"
        );

        let reloaded = UserLibrary::load_from(scratch.path()).expect("reload");
        let back = reloaded.get(&id).expect("saved brush is there");
        assert_eq!(back.collection.as_deref(), Some("Comics"));
        assert_eq!(back.collection(), "Comics");
        assert_eq!(back.category, "Inks & pens");
    }

    /// A library written before collections existed names none of them, and has
    /// to load as "no choice made" rather than failing or arriving blank.
    #[test]
    fn a_library_from_before_collections_still_loads() {
        let old = r#"(
            version: 1,
            presets: [(
                id: "user/old",
                name: "Old",
                category: "Inks & pens",
                brush: (size: 12.0),
            )],
        )"#;
        let presets = parse_library(old).expect("an older library still parses");
        assert_eq!(presets[0].collection, None);
        // And the brush still files where it always did.
        assert_eq!(presets[0].collection(), "Inks & pens");
    }

    /// A brush with no choice made and nothing to fall back on has to answer
    /// *something*, or the picker would have to guess.
    #[test]
    fn an_empty_collection_falls_through_to_the_category() {
        let mut preset = BrushPreset::unsaved("X", Brush::default());
        assert_eq!(preset.collection(), "My brushes");
        preset.collection = Some(String::new());
        assert_eq!(preset.collection(), "My brushes");
        preset.collection = Some("Comics".to_string());
        assert_eq!(preset.collection(), "Comics");
    }

    /// Twenty brushes filed correctly across six collections are twenty
    /// brushes somebody has to go and find.
    #[test]
    fn an_import_lands_in_one_collection_without_losing_its_style() {
        let scratch = Scratch::new("imported");
        fs::create_dir_all(&scratch.0).expect("scratch");
        let file = scratch.0.join("pack.ron");
        fs::write(
            &file,
            r#"(version: 1, presets: [
                (id: "pack/a", name: "A", category: "Charcoal, chalk & pastel", brush: ()),
                (id: "pack/b", name: "B", category: "Markers", brush: (), collection: Some("Mine")),
            ])"#,
        )
        .expect("write");

        let mut library = UserLibrary::load_from(scratch.path()).expect("load");
        let added = library.import_file(&file).expect("import");

        assert_eq!(added[0].collection(), IMPORTED);
        // The classifier's reading is still underneath, so moving the brush out
        // of "Imported" puts it back among its own kind.
        assert_eq!(added[0].category, "Charcoal, chalk & pastel");
        // A preset that already names a collection is somebody's own export
        // coming home, and their grouping is not the importer's to overwrite.
        assert_eq!(added[1].collection(), "Mine");
    }

    /// The one that matters. A shipped preset lives in the binary and is
    /// replaced wholesale by every update, so a user's re-grouping of one has
    /// to be written somewhere else — and has to find the brush again by *id*,
    /// because the release it lands in will have added, removed and reordered
    /// brushes around it.
    #[test]
    fn a_shipped_brushs_collection_survives_the_shipped_library_being_replaced() {
        let scratch = Scratch::new("assign-shipped");
        let mut library = UserLibrary::load_from(scratch.path()).expect("load");
        library.assign("umber/ink", Some("Comics")).expect("assign");
        // Not by adding a copy of somebody else's brush to the user's own.
        assert!(library.presets().is_empty());

        let text = std::fs::read_to_string(scratch.path().join("brushes.ron")).expect("read");
        assert!(text.contains("umber/ink"), "not written down: {text}");

        // The next release: the shipped library rebuilt from scratch, with a
        // brush inserted ahead of the filed one and another taken away, so
        // anything that had remembered a *position* comes back with the wrong
        // brush or none.
        let reloaded = UserLibrary::load_from(scratch.path()).expect("reload");
        let mut shipped = builtin().to_vec();
        shipped.insert(
            0,
            BrushPreset {
                id: "umber/new-next-release".to_string(),
                ..BrushPreset::unsaved("New", Brush::default())
            },
        );
        shipped.retain(|preset| preset.id != "umber/marker");
        reloaded.apply_collections(&mut shipped);

        let ink = shipped
            .iter()
            .find(|preset| preset.id == "umber/ink")
            .expect("still shipped");
        assert_eq!(ink.collection(), "Comics");
        // Exactly one brush moved, and it is that one.
        assert_eq!(
            shipped
                .iter()
                .filter(|preset| preset.collection() == "Comics")
                .count(),
            1
        );
    }

    #[test]
    fn taking_a_shipped_brushs_collection_off_puts_it_back_among_its_own_kind() {
        let scratch = Scratch::new("unassign-shipped");
        let mut library = UserLibrary::load_from(scratch.path()).expect("load");
        library.assign("umber/ink", Some("Comics")).expect("assign");
        library.assign("umber/ink", None).expect("unassign");
        assert!(library.collections().is_empty());

        let reloaded = UserLibrary::load_from(scratch.path()).expect("reload");
        let mut shipped = builtin().to_vec();
        reloaded.apply_collections(&mut shipped);
        let ink = shipped.iter().find(|p| p.id == "umber/ink").expect("ink");
        // Back to what `style::classify` made of it when the library was built.
        assert_eq!(ink.collection(), "Inks & pens");
    }

    /// A brush the library holds keeps its collection on the preset, so the
    /// choice travels with the brush into an export instead of being left
    /// behind in a table that refers to it.
    #[test]
    fn a_brush_the_library_holds_carries_its_own_collection() {
        let scratch = Scratch::new("assign-own");
        let mut library = UserLibrary::load_from(scratch.path()).expect("load");
        let id = library
            .save(BrushPreset::unsaved("Nib", Brush::default()), None)
            .expect("save");
        library.assign(&id, Some("Comics")).expect("assign");

        assert!(
            library.collections().is_empty(),
            "a brush of its own does not belong in the table"
        );
        assert_eq!(library.get(&id).unwrap().collection(), "Comics");

        let reloaded = UserLibrary::load_from(scratch.path()).expect("reload");
        assert_eq!(reloaded.get(&id).unwrap().collection(), "Comics");
    }

    /// A collection with nothing in it has nothing to derive it from, so the
    /// only thing that can carry it across a restart is the file.
    #[test]
    fn a_collection_the_user_made_survives_the_file() {
        let scratch = Scratch::new("made");
        let mut library = UserLibrary::load_from(scratch.path()).expect("load");
        assert_eq!(
            library.create_collection("Comics", &[]).expect("create"),
            NewCollection::Created
        );
        assert_eq!(library.made_collections(), ["Comics"]);
        // Not by inventing a brush to hang it on.
        assert!(library.presets().is_empty());

        let text = std::fs::read_to_string(scratch.path().join("brushes.ron")).expect("read");
        assert!(text.contains("Comics"), "not written down: {text}");

        let reloaded = UserLibrary::load_from(scratch.path()).expect("reload");
        assert_eq!(reloaded.made_collections(), ["Comics"]);
    }

    /// Two rows of one name are two places to drag a brush into and one place
    /// to look for it afterwards. Every way of arriving at the same name — the
    /// caller's derived list, a brush already filed there, one made a moment
    /// ago, and [`IMPORTED`], which an import can conjure at any time — has to
    /// be refused.
    #[test]
    fn a_name_already_in_use_does_not_make_a_second_collection() {
        let scratch = Scratch::new("made-clash");
        let mut library = UserLibrary::load_from(scratch.path()).expect("load");

        let derived = vec!["Inks & pens".to_owned()];
        assert_eq!(
            library
                .create_collection("Inks & pens", &derived)
                .expect("derived"),
            NewCollection::Exists
        );
        // Case and stray space are not a second collection either.
        assert_eq!(
            library
                .create_collection("  inks & PENS ", &derived)
                .expect("folded"),
            NewCollection::Exists
        );
        assert_eq!(
            library.create_collection(IMPORTED, &[]).expect("imported"),
            NewCollection::Exists
        );
        // A collection a brush of the library's own is filed under is derived
        // too, and the caller need not have said so.
        library
            .save(
                BrushPreset {
                    collection: Some("Comics".to_owned()),
                    ..BrushPreset::unsaved("Nib", Brush::default())
                },
                None,
            )
            .expect("save");
        assert_eq!(
            library.create_collection("Comics", &[]).expect("member"),
            NewCollection::Exists
        );

        // And one made a moment ago is not made twice.
        assert_eq!(
            library.create_collection("Studies", &[]).expect("first"),
            NewCollection::Created
        );
        assert_eq!(
            library.create_collection("studies", &[]).expect("again"),
            NewCollection::Exists
        );
        assert_eq!(library.made_collections(), ["Studies"]);

        // An empty name is a field somebody has not finished filling in, not a
        // collection called nothing.
        assert_eq!(
            library.create_collection("   ", &[]).expect("blank"),
            NewCollection::Unnamed
        );
        assert_eq!(library.made_collections(), ["Studies"]);
    }

    /// The merged list is rebuilt on every save, delete, import and move, and
    /// it is built from the presets — which an empty collection has none of.
    /// The list the app groups by therefore has to come from here as well, or
    /// the collection is gone before a brush can be dragged into it.
    #[test]
    fn an_empty_collection_outlives_a_rebuild_of_the_merged_list() {
        let scratch = Scratch::new("made-resync");
        let mut library = UserLibrary::load_from(scratch.path()).expect("load");
        library.create_collection("Comics", &[]).expect("create");

        // What `brushlib::resync` does: everything shipped, then everything
        // here, with the recorded collections stamped back on. Nothing in it
        // mentions "Comics", because no brush is in it yet.
        let mut merged = builtin().to_vec();
        merged.extend(library.presets().iter().cloned());
        library.apply_collections(&mut merged);
        assert!(!merged.iter().any(|p| p.collection() == "Comics"));
        // …and the library still knows about it, which is what puts the row
        // back on the rail.
        assert_eq!(library.made_collections(), ["Comics"]);

        // A brush dragged in afterwards files under it, and taking the brush
        // out again leaves the collection where it was: making a collection and
        // emptying it are not the same act.
        let id = library
            .save(BrushPreset::unsaved("Nib", Brush::default()), None)
            .expect("save");
        library.assign(&id, Some("Comics")).expect("assign");
        assert_eq!(library.get(&id).unwrap().collection(), "Comics");
        library.assign(&id, None).expect("unassign");
        assert_eq!(library.made_collections(), ["Comics"]);
    }

    /// The field is new, so every `brushes.ron` in existence is written without
    /// it. Refusing one would put somebody's whole collection out of reach over
    /// a list of collections they have not made yet.
    #[test]
    fn a_library_from_before_made_collections_still_loads() {
        let old = r#"(
            version: 1,
            presets: [(
                id: "user/old",
                name: "Old",
                category: "Inks & pens",
                brush: (size: 12.0),
            )],
        )"#;
        let library = parse(old).expect("an older library still parses");
        assert_eq!(library.presets.len(), 1);
        assert!(library.made_collections.is_empty());
    }

    /// A library nobody has added a collection to must be written exactly as it
    /// was, so the field costs nothing to have added.
    #[test]
    fn a_library_with_no_made_collections_does_not_write_the_field() {
        let text = to_ron(builtin()).expect("serialise");
        assert!(
            !text.contains("made_collections"),
            "an empty list should not reach the file"
        );
    }

    #[test]
    fn two_spellings_of_one_collection_are_one_collection() {
        assert!(same_collection("My brushes", "my brushes"));
        assert!(same_collection(" Comics ", "Comics"));
        assert!(!same_collection("Comics", "Comic"));
        assert!(!same_collection("", "Comics"));
    }

    #[test]
    fn saving_over_an_id_replaces_rather_than_duplicates() {
        let scratch = Scratch::new("replace");
        let mut library = UserLibrary::load_from(scratch.path()).expect("load");
        let id = library
            .save(BrushPreset::unsaved("Liner", Brush::default()), None)
            .expect("save");

        let mut edited = library.get(&id).expect("saved").clone();
        edited.brush.size = 99.0;
        library.save(edited, None).expect("save again");

        assert_eq!(library.presets().len(), 1);
        assert_eq!(library.get(&id).unwrap().brush.size, 99.0);
    }

    #[test]
    fn two_brushes_with_one_name_get_different_ids() {
        let scratch = Scratch::new("collide");
        let mut library = UserLibrary::load_from(scratch.path()).expect("load");
        let first = library
            .save(BrushPreset::unsaved("Liner", Brush::default()), None)
            .expect("first");
        let second = library
            .save(BrushPreset::unsaved("Liner", Brush::default()), None)
            .expect("second");
        assert_ne!(first, second);
        assert_eq!(library.presets().len(), 2);
    }

    #[test]
    fn renaming_keeps_the_id_and_deleting_reports_whether_it_hit() {
        let scratch = Scratch::new("rename");
        let mut library = UserLibrary::load_from(scratch.path()).expect("load");
        let id = library
            .save(BrushPreset::unsaved("Old", Brush::default()), None)
            .expect("save");

        assert!(library.rename(&id, "New").expect("rename"));
        assert_eq!(library.get(&id).unwrap().name, "New");
        assert!(!library.rename("user/nope", "New").expect("miss"));

        assert!(library.delete(&id).expect("delete"));
        assert!(!library.delete(&id).expect("delete again"));
        assert!(library.presets().is_empty());
    }

    /// A tip is a bitmap and the library is text; this is the whole reason the
    /// library became a directory. The mask has to come back exactly, or every
    /// stamp brush changes shape each time Umber is restarted.
    #[test]
    fn a_tipped_brush_survives_a_reload_byte_for_byte() {
        let scratch = Scratch::new("tip");
        let mut library = UserLibrary::load_from(scratch.path()).expect("load");

        let coverage: Vec<u8> = (0..(9 * 4)).map(|i| (i * 11 % 256) as u8).collect();
        let mask = TipMask::new(9, 4, coverage.clone()).expect("mask");
        let id = library
            .save(BrushPreset::unsaved("Stamp", Brush::default()), Some(mask))
            .expect("save");

        let name = library
            .get(&id)
            .and_then(|preset| preset.tip.clone())
            .expect("the saved preset names its tip");
        assert!(scratch.tip_file(&name).exists(), "no PNG was written");

        let reloaded = UserLibrary::load_from(scratch.path()).expect("reload");
        let preset = reloaded.get(&id).expect("saved brush is there");
        assert_eq!(preset.tip.as_deref(), Some(name.as_str()));
        let back = reloaded.tip(&name).expect("the mask came back");
        assert_eq!(back.width(), 9);
        assert_eq!(back.height(), 4);
        assert_eq!(back.coverage(), coverage);
    }

    #[test]
    fn updating_a_stamp_brush_keeps_its_stamp() {
        // `None` means "leave the tip alone", which is what the editor's Update
        // passes. Reading it as "no tip" would silently turn every saved stamp
        // brush round the first time its size was changed.
        let scratch = Scratch::new("keep-tip");
        let mut library = UserLibrary::load_from(scratch.path()).expect("load");
        let mask = TipMask::new(2, 2, vec![1, 2, 3, 4]).expect("mask");
        let id = library
            .save(BrushPreset::unsaved("Stamp", Brush::default()), Some(mask))
            .expect("save");

        let mut edited = library.get(&id).expect("saved").clone();
        edited.brush.size = 64.0;
        library.save(edited, None).expect("update");

        let preset = library.get(&id).expect("still there");
        assert_eq!(preset.brush.size, 64.0);
        let name = preset.tip.clone().expect("the tip is still named");
        assert_eq!(library.tip(&name).expect("mask").coverage(), [1, 2, 3, 4]);
    }

    #[test]
    fn a_tip_nobody_names_any_more_is_deleted_with_its_brush() {
        // Otherwise the directory grows a picture per discarded experiment and
        // never gives one back.
        let scratch = Scratch::new("prune");
        let mut library = UserLibrary::load_from(scratch.path()).expect("load");
        let mask = TipMask::new(2, 2, vec![255; 4]).expect("mask");
        let id = library
            .save(BrushPreset::unsaved("Stamp", Brush::default()), Some(mask))
            .expect("save");
        let name = library.get(&id).unwrap().tip.clone().expect("named");
        assert!(scratch.tip_file(&name).exists());

        library.delete(&id).expect("delete");
        assert!(
            !scratch.tip_file(&name).exists(),
            "the mask was left behind"
        );
        assert!(library.tip(&name).is_none());
    }

    #[test]
    fn clearing_the_tip_field_takes_the_tip_off() {
        let scratch = Scratch::new("untip");
        let mut library = UserLibrary::load_from(scratch.path()).expect("load");
        let mask = TipMask::new(2, 2, vec![255; 4]).expect("mask");
        let id = library
            .save(BrushPreset::unsaved("Stamp", Brush::default()), Some(mask))
            .expect("save");

        let mut round = library.get(&id).expect("saved").clone();
        round.tip = None;
        library.save(round, None).expect("save round");

        assert!(library.get(&id).unwrap().tip.is_none());
        assert!(library.tips().is_empty(), "the orphan should have gone");
    }

    #[test]
    fn importing_a_ron_drops_a_tip_reference_it_cannot_resolve() {
        // An Umber library is text, so a tip it names is not in the file. A
        // reference left pointing at nothing would be a brush that silently
        // paints round on one machine and square on another; dropping it means
        // the brush arrives round on both, which is at least honest.
        let scratch = Scratch::new("dangling");
        fs::create_dir_all(&scratch.0).expect("scratch");
        let file = scratch.0.join("exported.ron");
        fs::write(
            &file,
            r#"(version: 1, presets: [(id: "user/s", name: "S", brush: (), tip: Some("gone"))])"#,
        )
        .expect("write");

        let mut library = UserLibrary::load_from(scratch.path()).expect("load");
        let added = library.import_file(&file).expect("import");
        assert_eq!(added.len(), 1);
        assert!(added[0].tip.is_none());
    }

    /// Somebody has a `brushes.ron` from before tips existed. Losing it — or
    /// quietly leaving it behind and starting again over the top — is the
    /// failure this guards.
    #[test]
    fn a_flat_library_is_migrated_into_the_directory() {
        let scratch = Scratch::new("migrate");
        fs::create_dir_all(&scratch.0).expect("scratch");
        fs::write(
            scratch.legacy(),
            r#"(version: 1, presets: [(id: "user/old", name: "Old", brush: (size: 33.0))])"#,
        )
        .expect("write the old library");

        let library = UserLibrary::load_from(scratch.path()).expect("load");
        assert!(library.migrated());
        assert_eq!(library.presets().len(), 1);
        assert_eq!(library.get("user/old").unwrap().brush.size, 33.0);

        // Written into the new layout, so the next run does not migrate again…
        assert!(scratch.path().join(UserLibrary::FILE_NAME).exists());
        // …and the original is still there. A migration that deletes the only
        // copy of somebody's collection has to be right first time.
        assert!(scratch.legacy().exists());

        let again = UserLibrary::load_from(scratch.path()).expect("reload");
        assert!(!again.migrated(), "the second load must not migrate");
        assert_eq!(again.presets().len(), 1);
    }

    #[test]
    fn a_directory_that_already_has_brushes_ignores_the_old_file() {
        // The old file is left in place, so an older Umber can keep writing to
        // it. Reading it back over a newer library would undo everything done
        // since the move.
        let scratch = Scratch::new("no-remigrate");
        let mut library = UserLibrary::load_from(scratch.path()).expect("load");
        library
            .save(BrushPreset::unsaved("New", Brush::default()), None)
            .expect("save");
        fs::write(
            scratch.legacy(),
            r#"(version: 1, presets: [(id: "user/stale", name: "Stale", brush: ())])"#,
        )
        .expect("write a stale old library");

        let reloaded = UserLibrary::load_from(scratch.path()).expect("reload");
        assert!(!reloaded.migrated());
        assert_eq!(reloaded.presets().len(), 1);
        assert_eq!(reloaded.presets()[0].name, "New");
    }

    #[test]
    fn a_tip_that_will_not_decode_is_a_warning_rather_than_a_dead_library() {
        // One unreadable picture must not put the whole collection out of
        // reach — but it must not be silent either.
        let scratch = Scratch::new("bad-tip");
        let mut library = UserLibrary::load_from(scratch.path()).expect("load");
        library
            .save(BrushPreset::unsaved("Brush", Brush::default()), None)
            .expect("save");
        fs::create_dir_all(scratch.path().join("tips")).expect("tips");
        fs::write(scratch.tip_file("broken"), b"not a png").expect("write");

        let reloaded = UserLibrary::load_from(scratch.path()).expect("reload");
        assert_eq!(reloaded.presets().len(), 1);
        assert_eq!(reloaded.warnings().len(), 1, "{:?}", reloaded.warnings());
        assert!(reloaded.warnings()[0].contains("broken"));
    }

    #[test]
    fn slugs_are_safe_and_collapse_runs() {
        assert_eq!(slug("My Brush!!"), "my-brush");
        assert_eq!(slug("  spaced  out  "), "spaced-out");
        assert_eq!(slug("Ærø 12"), "r-12");
        assert_eq!(slug("!!!"), "");
    }
}
