#!/bin/sh
# Download the vetted CC0 brush packs into assets/brushes/.
#
# The POSIX twin of tools/fetch-brushes.ps1 — read that one for why the packs
# are fetched rather than vendored, and why the previews are dropped. Both
# scripts must produce the same tree; if you change one, change the other.
#
#   sh tools/fetch-brushes.sh
#   cargo run -p umber-core --example build-brush-library

set -eu

FORCE=0
[ "${1:-}" = "--force" ] && FORCE=1

REPO_ROOT=$(CDPATH= cd -- "$(dirname -- "$0")/.." && pwd)
BRUSH_ROOT="$REPO_ROOT/assets/brushes"

# Pack table: id | name | url | home | archive root | licence | licence file | authors | format
# One line per pack, fields separated by '|'.
PACKS='mypaint|MyPaint default brushes 2.0.2|https://github.com/mypaint/mypaint-brushes/archive/refs/tags/v2.0.2.zip|https://github.com/mypaint/mypaint-brushes|mypaint-brushes-2.0.2|CC0-1.0|Licenses.dep5|Martin Renold and the MyPaint Development Team; Ramón Miranda; Marcelo "Tanda" Cerviño; David Revoy; Guillaume Loussarévian; Brien Dieterle|.myb (MyPaint, JSON)'

unpack() {
    # $1 archive, $2 destination
    if command -v unzip >/dev/null 2>&1; then
        unzip -q "$1" -d "$2"
    elif command -v bsdtar >/dev/null 2>&1; then
        bsdtar -xf "$1" -C "$2"
    else
        echo "need either unzip or bsdtar to unpack $1" >&2
        return 1
    fi
}

mkdir -p "$BRUSH_ROOT"

# The header of the licence record; each pack appends its own section below.
cat >"$BRUSH_ROOT/LICENSES.md" <<'EOF'
# Brush pack licences

Generated by `tools/fetch-brushes.ps1` (or its `.sh` twin). Do not edit by hand.

These packs are downloaded, not vendored: everything under this directory
except this file is git-ignored. The library Umber ships is generated from
them by `cargo run -p umber-core --example build-brush-library`.

Preview thumbnails (`*_prev.png`) are deliberately **not** downloaded. In the
MyPaint pack the brush settings are CC0 but some previews are CC-BY, and not
having the files is the surest way not to ship them.

EOF

echo "$PACKS" | while IFS='|' read -r id name url home root licence licfile authors format; do
    echo "$name"
    target="$BRUSH_ROOT/$id"
    if [ -d "$target" ] && [ "$FORCE" -eq 0 ]; then
        echo "  already present, skipping (use --force to refresh)"
        continue
    fi

    work=$(mktemp -d)
    trap 'rm -rf "$work"' EXIT

    echo "  downloading $url"
    curl -sSL --fail -o "$work/pack.zip" "$url"
    unpack "$work/pack.zip" "$work"

    extracted="$work/$root"
    if [ ! -d "$extracted" ]; then
        echo "  archive did not contain '$root'; skipping" >&2
        continue
    fi

    # The licence check, against the archive's own file rather than a note here.
    if [ ! -f "$extracted/$licfile" ]; then
        echo "  no $licfile in the download; refusing to keep it" >&2
        continue
    fi
    if ! grep -q 'Files: brushes/\*' "$extracted/$licfile" ||
        ! grep -q "License: $licence" "$extracted/$licfile"; then
        echo "  $licfile does not state $licence for the brushes; refusing to keep it" >&2
        continue
    fi
    echo "  licence verified: $licence"

    rm -rf "$target"
    mkdir -p "$target/brushes"

    # Settings only. The previews are CC-BY where the settings are CC0.
    (cd "$extracted" && find brushes -name '*.myb' -print) | while read -r rel; do
        mkdir -p "$target/$(dirname "$rel")"
        cp "$extracted/$rel" "$target/$rel"
    done
    for f in COPYING Licenses.dep5 Licenses.md AUTHORS; do
        [ -f "$extracted/$f" ] && cp "$extracted/$f" "$target/$f"
    done
    echo "  kept $(find "$target" -name '*.myb' | wc -l | tr -d ' ') brushes in assets/brushes/$id"

    cat >>"$BRUSH_ROOT/LICENSES.md" <<EOF
## $name

- **Directory:** \`assets/brushes/$id/\`
- **Source:** <$home>
- **Downloaded from:** <$url>
- **Licence:** $licence, verified against \`$licfile\` in the download itself
- **Authors:** $authors
- **Format:** $format

EOF
    echo "recorded the licence in $BRUSH_ROOT/LICENSES.md"

    rm -rf "$work"
    trap - EXIT
done

echo
echo "Next: cargo run -p umber-core --example build-brush-library"
